#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------

dimension.world-2=minecraft:primordial_caves

dimension.world0=* !minecraft:primordial_caves

dimension.world-1=minecraft:the_nether minecraft:nether

dimension.world1=minecraft:the_end minecraft:end