package net.minecraft.client.renderer.sodium.mixin;

/**
 * Accessor stub for compile-time reference.
 * The actual accessor is generated by Sodium mixins at runtime.
 * 
 * @see net.caffeinemc.mods.sodium.mixin.features.textures.NativeImageAccessor
 */
public interface NativeImageAccessor {
    long getPixels();
}
