//! The static table of bundled GUI sprites.

use super::*;

pub(super) const fn group(invert: bool) -> TextureGroup {
    if invert {
        TextureGroup::Invert
    } else {
        TextureGroup::Alpha
    }
}

pub(super) const SPRITES: &[SpriteDef] = &[
    SpriteDef {
        id: 1,
        stratum: 200,
        name: "crosshair",
        path: "/assets/minecraft/textures/gui/sprites/hud/crosshair.png",
        width: 15,
        height: 15,
        group: group(true),
    },
    SpriteDef {
        id: 2,
        stratum: 300,
        name: "hotbar-base",
        path: "/assets/minecraft/textures/gui/sprites/hud/hotbar.png",
        width: 182,
        height: 22,
        group: group(false),
    },
    SpriteDef {
        id: 3,
        stratum: 310,
        name: "hotbar-selection",
        path: "/assets/minecraft/textures/gui/sprites/hud/hotbar_selection.png",
        width: 24,
        height: 23,
        group: group(false),
    },
    SpriteDef {
        id: 4,
        stratum: 350,
        name: "armor-empty",
        path: "/assets/minecraft/textures/gui/sprites/hud/armor_empty.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 5,
        stratum: 350,
        name: "armor-half",
        path: "/assets/minecraft/textures/gui/sprites/hud/armor_half.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 6,
        stratum: 350,
        name: "armor-full",
        path: "/assets/minecraft/textures/gui/sprites/hud/armor_full.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 7,
        stratum: 360,
        name: "player-heart-container",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/container.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 8,
        stratum: 360,
        name: "player-heart-container",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/container_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 9,
        stratum: 360,
        name: "player-heart-container",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/container_hardcore.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 10,
        stratum: 360,
        name: "player-heart-container",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/container_hardcore_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 11,
        stratum: 360,
        name: "player-heart-normal",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/full.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 12,
        stratum: 360,
        name: "player-heart-normal",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/full_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 13,
        stratum: 360,
        name: "player-heart-normal",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/half.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 14,
        stratum: 360,
        name: "player-heart-normal",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/half_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 15,
        stratum: 360,
        name: "player-heart-normal",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/hardcore_full.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 16,
        stratum: 360,
        name: "player-heart-normal",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/hardcore_full_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 17,
        stratum: 360,
        name: "player-heart-normal",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/hardcore_half.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 18,
        stratum: 360,
        name: "player-heart-normal",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/hardcore_half_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 19,
        stratum: 360,
        name: "player-heart-poisoned",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/poisoned_full.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 20,
        stratum: 360,
        name: "player-heart-poisoned",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/poisoned_full_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 21,
        stratum: 360,
        name: "player-heart-poisoned",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/poisoned_half.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 22,
        stratum: 360,
        name: "player-heart-poisoned",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/poisoned_half_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 23,
        stratum: 360,
        name: "player-heart-poisoned",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/poisoned_hardcore_full.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 24,
        stratum: 360,
        name: "player-heart-poisoned",
        path:
            "/assets/minecraft/textures/gui/sprites/hud/heart/poisoned_hardcore_full_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 25,
        stratum: 360,
        name: "player-heart-poisoned",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/poisoned_hardcore_half.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 26,
        stratum: 360,
        name: "player-heart-poisoned",
        path:
            "/assets/minecraft/textures/gui/sprites/hud/heart/poisoned_hardcore_half_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 27,
        stratum: 360,
        name: "player-heart-withered",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/withered_full.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 28,
        stratum: 360,
        name: "player-heart-withered",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/withered_full_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 29,
        stratum: 360,
        name: "player-heart-withered",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/withered_half.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 30,
        stratum: 360,
        name: "player-heart-withered",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/withered_half_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 31,
        stratum: 360,
        name: "player-heart-withered",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/withered_hardcore_full.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 32,
        stratum: 360,
        name: "player-heart-withered",
        path:
            "/assets/minecraft/textures/gui/sprites/hud/heart/withered_hardcore_full_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 33,
        stratum: 360,
        name: "player-heart-withered",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/withered_hardcore_half.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 34,
        stratum: 360,
        name: "player-heart-withered",
        path:
            "/assets/minecraft/textures/gui/sprites/hud/heart/withered_hardcore_half_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 35,
        stratum: 360,
        name: "player-heart-frozen",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/frozen_full.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 36,
        stratum: 360,
        name: "player-heart-frozen",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/frozen_full_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 37,
        stratum: 360,
        name: "player-heart-frozen",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/frozen_half.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 38,
        stratum: 360,
        name: "player-heart-frozen",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/frozen_half_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 39,
        stratum: 360,
        name: "player-heart-frozen",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/frozen_hardcore_full.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 40,
        stratum: 360,
        name: "player-heart-frozen",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/frozen_hardcore_full_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 41,
        stratum: 360,
        name: "player-heart-frozen",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/frozen_hardcore_half.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 42,
        stratum: 360,
        name: "player-heart-frozen",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/frozen_hardcore_half_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 43,
        stratum: 360,
        name: "absorption-heart",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/absorbing_full.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 44,
        stratum: 360,
        name: "absorption-heart",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/absorbing_full_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 45,
        stratum: 360,
        name: "absorption-heart",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/absorbing_half.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 46,
        stratum: 360,
        name: "absorption-heart",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/absorbing_half_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 47,
        stratum: 360,
        name: "absorption-heart",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/absorbing_hardcore_full.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 48,
        stratum: 360,
        name: "absorption-heart",
        path:
            "/assets/minecraft/textures/gui/sprites/hud/heart/absorbing_hardcore_full_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 49,
        stratum: 360,
        name: "absorption-heart",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/absorbing_hardcore_half.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 50,
        stratum: 360,
        name: "absorption-heart",
        path:
            "/assets/minecraft/textures/gui/sprites/hud/heart/absorbing_hardcore_half_blinking.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 51,
        stratum: 400,
        name: "experience-background",
        path: "/assets/minecraft/textures/gui/sprites/hud/experience_bar_background.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 52,
        stratum: 410,
        name: "experience-progress",
        path: "/assets/minecraft/textures/gui/sprites/hud/experience_bar_progress.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 53,
        stratum: 510,
        name: "attack-crosshair-full",
        path: "/assets/minecraft/textures/gui/sprites/hud/crosshair_attack_indicator_full.png",
        width: 16,
        height: 16,
        group: group(false),
    },
    SpriteDef {
        id: 54,
        stratum: 500,
        name: "attack-crosshair-background",
        path:
            "/assets/minecraft/textures/gui/sprites/hud/crosshair_attack_indicator_background.png",
        width: 16,
        height: 4,
        group: group(false),
    },
    SpriteDef {
        id: 55,
        stratum: 510,
        name: "attack-crosshair-progress",
        path: "/assets/minecraft/textures/gui/sprites/hud/crosshair_attack_indicator_progress.png",
        width: 16,
        height: 4,
        group: group(false),
    },
    SpriteDef {
        id: 56,
        stratum: 520,
        name: "attack-hotbar-background",
        path: "/assets/minecraft/textures/gui/sprites/hud/hotbar_attack_indicator_background.png",
        width: 18,
        height: 18,
        group: group(false),
    },
    SpriteDef {
        id: 57,
        stratum: 530,
        name: "attack-hotbar-progress",
        path: "/assets/minecraft/textures/gui/sprites/hud/hotbar_attack_indicator_progress.png",
        width: 18,
        height: 18,
        group: group(false),
    },
    SpriteDef {
        id: 58,
        stratum: 600,
        name: "boss-bar-background",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/pink_background.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 59,
        stratum: 600,
        name: "boss-bar-background",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/blue_background.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 60,
        stratum: 600,
        name: "boss-bar-background",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/red_background.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 61,
        stratum: 600,
        name: "boss-bar-background",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/green_background.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 62,
        stratum: 600,
        name: "boss-bar-background",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/yellow_background.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 63,
        stratum: 600,
        name: "boss-bar-background",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/purple_background.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 64,
        stratum: 600,
        name: "boss-bar-background",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/white_background.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 65,
        stratum: 610,
        name: "boss-bar-progress",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/pink_progress.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 66,
        stratum: 610,
        name: "boss-bar-progress",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/blue_progress.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 67,
        stratum: 610,
        name: "boss-bar-progress",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/red_progress.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 68,
        stratum: 610,
        name: "boss-bar-progress",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/green_progress.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 69,
        stratum: 610,
        name: "boss-bar-progress",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/yellow_progress.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 70,
        stratum: 610,
        name: "boss-bar-progress",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/purple_progress.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 71,
        stratum: 610,
        name: "boss-bar-progress",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/white_progress.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 72,
        stratum: 600,
        name: "boss-bar-overlay-background",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/notched_6_background.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 73,
        stratum: 600,
        name: "boss-bar-overlay-background",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/notched_10_background.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 74,
        stratum: 600,
        name: "boss-bar-overlay-background",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/notched_12_background.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 75,
        stratum: 600,
        name: "boss-bar-overlay-background",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/notched_20_background.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 76,
        stratum: 610,
        name: "boss-bar-overlay-progress",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/notched_6_progress.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 77,
        stratum: 610,
        name: "boss-bar-overlay-progress",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/notched_10_progress.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 78,
        stratum: 610,
        name: "boss-bar-overlay-progress",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/notched_12_progress.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 79,
        stratum: 610,
        name: "boss-bar-overlay-progress",
        path: "/assets/minecraft/textures/gui/sprites/boss_bar/notched_20_progress.png",
        width: 182,
        height: 5,
        group: group(false),
    },
    SpriteDef {
        id: 80,
        stratum: 370,
        name: "hunger-empty",
        path: "/assets/minecraft/textures/gui/sprites/hud/food_empty.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 81,
        stratum: 370,
        name: "hunger-half",
        path: "/assets/minecraft/textures/gui/sprites/hud/food_half.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 82,
        stratum: 370,
        name: "hunger-full",
        path: "/assets/minecraft/textures/gui/sprites/hud/food_full.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 83,
        stratum: 370,
        name: "hunger-effect-empty",
        path: "/assets/minecraft/textures/gui/sprites/hud/food_empty_hunger.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 84,
        stratum: 370,
        name: "hunger-effect-half",
        path: "/assets/minecraft/textures/gui/sprites/hud/food_half_hunger.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 85,
        stratum: 370,
        name: "hunger-effect-full",
        path: "/assets/minecraft/textures/gui/sprites/hud/food_full_hunger.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 86,
        stratum: 380,
        name: "air-full",
        path: "/assets/minecraft/textures/gui/sprites/hud/air.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 87,
        stratum: 380,
        name: "air-popping",
        path: "/assets/minecraft/textures/gui/sprites/hud/air_bursting.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 88,
        stratum: 380,
        name: "air-empty",
        path: "/assets/minecraft/textures/gui/sprites/hud/air_empty.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 89,
        stratum: 390,
        name: "mount-heart-container",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/vehicle_container.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 90,
        stratum: 390,
        name: "mount-heart-full",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/vehicle_full.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: 91,
        stratum: 390,
        name: "mount-heart-half",
        path: "/assets/minecraft/textures/gui/sprites/hud/heart/vehicle_half.png",
        width: 9,
        height: 9,
        group: group(false),
    },
    SpriteDef {
        id: GUI_POST_EFFECT_INVERT_ID,
        stratum: 80,
        name: "post-effect-invert",
        path: "/assets/minecraft/textures/misc/rust_generated_white.png",
        width: 1,
        height: 1,
        group: group(true),
    },
    SpriteDef {
        id: GUI_POST_EFFECT_CREEPER_ID,
        stratum: 80,
        name: "post-effect-creeper",
        path: "/assets/minecraft/textures/misc/rust_generated_white.png",
        width: 1,
        height: 1,
        group: group(false),
    },
    SpriteDef {
        id: GUI_POST_EFFECT_SPIDER_ID,
        stratum: 80,
        name: "post-effect-spider",
        path: "/assets/minecraft/textures/misc/rust_generated_white.png",
        width: 1,
        height: 1,
        group: group(false),
    },
];
