[package]
name = "mattmc-rust"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"

[[bin]]
name = "mattmc-rust"
path = "src/main/rust/main.rs"

[dependencies]
winit = "0.28"
vulkano = "0.34"
bytemuck = { version = "1.14", features = ["derive"] }
raw-window-handle = "0.5"
glam = "0.24"

[profile.dev]
opt-level = 1
debug = true

[profile.release]
opt-level = 3
debug = true
lto = true
