package net.vulkanic.world;

import java.util.List;
import java.util.Map;
import net.minecraft.client.Camera;
import net.minecraft.client.renderer.state.SkyRenderState;
import net.vulkanic.bridge.VulkanicGalBridge;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SkyProceduralAdmissionTest {
    @org.junit.jupiter.api.BeforeAll
    static void bootstrap() {
        net.minecraft.SharedConstants.tryDetectVersion();
        net.minecraft.server.Bootstrap.bootStrap();
    }

    @Test
    @SuppressWarnings("unchecked")
    void darkDiscCopiesFrozensLocalBottomFanWithoutBakingCameraOrDrawTranslation() throws Exception {
        var renderer = RustGalWorldPrimitiveRenderer.class;
        var quads = renderer.getDeclaredField("PENDING_MATERIAL_QUADS");
        quads.setAccessible(true);
        var pending = (List<VulkanicGalBridge.WorldMaterialQuadRecord>) quads.get(null);
        var emit = renderer.getDeclaredMethod("enqueueVanillaDarkDiscLocked", Camera.class);
        emit.setAccessible(true);
        var width = renderer.getDeclaredField("pendingViewportWidth");
        var height = renderer.getDeclaredField("pendingViewportHeight");
        width.setAccessible(true);
        height.setAccessible(true);
        int oldWidth = width.getInt(null), oldHeight = height.getInt(null);
        int checkpoint = pending.size();
        try {
            width.setInt(null, 1280);
            height.setInt(null, 720);
            emit.invoke(null, new Camera());
            var fan = List.copyOf(pending.subList(checkpoint, pending.size()));
            assertEquals(8, fan.size());
            var first = fan.getFirst();
            assertEquals(512.0F, first.p1X(), 0.001F);
            assertEquals(0.0F, first.p1Z(), 0.001F);
            assertEquals(362.03867F, first.p2X(), 0.001F);
            assertEquals(-362.03867F, first.p2Z(), 0.001F);
            for (var triangle : fan) {
                assertEquals(RustGalWorldPrimitiveRenderer.MATERIAL_ID_SKY_DARK_DISC, triangle.materialId());
                assertEquals(RustGalWorldPrimitiveRenderer.DEPTH_POLICY_TEST_NO_WRITE, triangle.depthPolicy());
                assertEquals(RustGalWorldPrimitiveRenderer.CULL_BACK, triangle.cullPolicy());
                assertEquals(-16.0F, triangle.p0Y());
                assertEquals(-16.0F, triangle.p1Y());
                assertEquals(-16.0F, triangle.p2Y());
                assertEquals(-16.0F, triangle.p3Y());
                assertEquals(triangle.p0X(), triangle.p3X());
                assertEquals(triangle.p0Z(), triangle.p3Z());
                assertTrue(triangle.p1Z() * triangle.p2X() - triangle.p1X() * triangle.p2Z() > 0.0F,
                    "Frozen's bottom fan faces upward");
            }
            pending.subList(checkpoint, pending.size()).clear();
            var camera = new Camera();
            var position = Camera.class.getDeclaredMethod("setPosition", double.class, double.class, double.class);
            var rotation = Camera.class.getDeclaredMethod("setRotation", float.class, float.class);
            position.setAccessible(true);
            rotation.setAccessible(true);
            position.invoke(camera, 167.5, 39.62, 553.5);
            rotation.invoke(camera, 105.0F, 15.0F);
            emit.invoke(null, camera);
            assertEquals(fan, pending.subList(checkpoint, pending.size()));
        } finally {
            pending.subList(checkpoint, pending.size()).clear();
            width.setInt(null, oldWidth);
            height.setInt(null, oldHeight);
        }
    }

    @Test
    @SuppressWarnings("unchecked")
    void starsDoNotRequireAJavaCopyOfRustsPrivateWhiteTexture() throws Exception {
        var renderer = RustGalWorldPrimitiveRenderer.class;
        var textures = renderer.getDeclaredField("WORLD_MESH_TEXTURES");
        var quads = renderer.getDeclaredField("PENDING_MATERIAL_QUADS");
        var width = renderer.getDeclaredField("pendingViewportWidth");
        var height = renderer.getDeclaredField("pendingViewportHeight");
        width.setAccessible(true);
        height.setAccessible(true);
        int oldWidth = width.getInt(null), oldHeight = height.getInt(null);
        textures.setAccessible(true);
        quads.setAccessible(true);
        var assets = (Map<Integer, VulkanicGalBridge.WorldMeshTextureAssetRecord>) textures.get(null);
        var pending = (List<VulkanicGalBridge.WorldMaterialQuadRecord>) quads.get(null);
        int white = RustGalWorldPrimitiveRenderer.MATERIAL_TEXTURE_GENERATED_WHITE;
        assertFalse(assets.containsKey(white), "white is generated by Rust, not a Java atlas asset");
        int checkpoint = pending.size();
        var emit = renderer.getDeclaredMethod("enqueueVanillaCelestialQuadsLocked", SkyRenderState.class, Camera.class);
        emit.setAccessible(true);
        var state = new SkyRenderState();
        state.starBrightness = 0.5F;
        state.rainBrightness = 1.0F;
        state.timeOfDay = 0.5F;
        try {
            width.setInt(null, 1280);
            height.setInt(null, 720);
            emit.invoke(null, state, new Camera());
            assertEquals(RustGalWorldPrimitiveRenderer.MATERIAL_ID_CELESTIAL, pending.get(checkpoint).materialId());
            assertEquals(RustGalWorldPrimitiveRenderer.MATERIAL_ID_CELESTIAL, pending.get(checkpoint + 1).materialId());
            long stars = pending.subList(checkpoint, pending.size()).stream()
                .filter(quad -> quad.textureId() == white).count();
            assertEquals(780, stars, "night must publish the complete deterministic star field");
            assertTrue(pending.subList(checkpoint, pending.size()).stream()
                .filter(quad -> quad.textureId() == white)
                .allMatch(quad -> quad.materialId() == RustGalWorldPrimitiveRenderer.MATERIAL_ID_SKY_STARS));
            assertFalse(assets.containsKey(white), "extraction must not fabricate Java GPU ownership");
            var originGeometry = List.copyOf(pending.subList(checkpoint, pending.size()));
            pending.subList(checkpoint, pending.size()).clear();
            var camera = new Camera();
            var position = Camera.class.getDeclaredMethod("setPosition", double.class, double.class, double.class);
            var rotation = Camera.class.getDeclaredMethod("setRotation", float.class, float.class);
            position.setAccessible(true);
            rotation.setAccessible(true);
            position.invoke(camera, 150.5, 101.62, 530.5);
            rotation.invoke(camera, 105.0F, 10.0F);
            emit.invoke(null, state, camera);
            assertEquals(originGeometry.size(), pending.size() - checkpoint);
            for (int index = 0; index < originGeometry.size(); index++) {
                assertEquals(originGeometry.get(index), pending.get(checkpoint + index),
                    "celestial geometry is camera-relative; GAL view applies camera rotation exactly once");
            }
            pending.subList(checkpoint, pending.size()).clear();
            state.starBrightness = 0.0F;
            emit.invoke(null, state, new Camera());
            assertEquals(2, pending.size() - checkpoint, "daylight emits sun/moon, not stale stars");
            for (int phase = 0; phase < 8; phase++) {
                pending.subList(checkpoint, pending.size()).clear();
                state.moonPhase = phase;
                emit.invoke(null, state, camera);
                var moon = pending.get(checkpoint + 1);
                assertEquals((phase % 4 + 1) / 4.0F, moon.uv0U());
                assertEquals((phase % 4) / 4.0F, moon.uv2U());
                assertEquals((phase / 4) / 2.0F, moon.uv0V());
                assertEquals((phase / 4 + 1) / 2.0F, moon.uv2V());
                assertEquals(RustGalWorldPrimitiveRenderer.WORLD_WINDING_CW, moon.winding());
                assertEquals(RustGalWorldPrimitiveRenderer.CULL_BACK, moon.cullPolicy());
            }
        } finally {
            pending.subList(checkpoint, pending.size()).clear();
            width.setInt(null, oldWidth);
            height.setInt(null, oldHeight);
        }
    }
}
