package net.minecraft.world.entity.ai.attributes;

import com.google.common.collect.ImmutableMap;
import net.logging.LogUtils;
import java.util.Map;

import net.alexscaves.server.entity.living.AtlatitanEntity;
import net.alexsmobs.entity.*;
import net.minecraft.Util;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.GlowSquid;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.entity.MobCategory;
import net.minecraft.world.entity.ambient.Bat;
import net.minecraft.world.entity.animal.AbstractFish;
import net.minecraft.world.entity.animal.Bee;
import net.minecraft.world.entity.animal.Cat;
import net.minecraft.world.entity.animal.Chicken;
import net.minecraft.world.entity.animal.Cow;
import net.minecraft.world.entity.animal.Dolphin;
import net.minecraft.world.entity.animal.Fox;
import net.minecraft.world.entity.animal.HappyGhast;
import net.minecraft.world.entity.animal.IronGolem;
import net.minecraft.world.entity.animal.Ocelot;
import net.minecraft.world.entity.animal.Panda;
import net.minecraft.world.entity.animal.Parrot;
import net.minecraft.world.entity.animal.Pig;
import net.minecraft.world.entity.animal.PolarBear;
import net.minecraft.world.entity.animal.Rabbit;
import net.minecraft.world.entity.animal.SnowGolem;
import net.minecraft.world.entity.animal.Squid;
import net.minecraft.world.entity.animal.Turtle;
import net.minecraft.world.entity.animal.allay.Allay;
import net.minecraft.world.entity.animal.armadillo.Armadillo;
import net.minecraft.world.entity.animal.axolotl.Axolotl;
import net.minecraft.world.entity.animal.camel.Camel;
import net.minecraft.world.entity.animal.coppergolem.CopperGolem;
import net.minecraft.world.entity.animal.frog.Frog;
import net.minecraft.world.entity.animal.frog.Tadpole;
import net.minecraft.world.entity.animal.goat.Goat;
import net.minecraft.world.entity.animal.horse.AbstractChestedHorse;
import net.minecraft.world.entity.animal.horse.AbstractHorse;
import net.minecraft.world.entity.animal.horse.Llama;
import net.minecraft.world.entity.animal.horse.SkeletonHorse;
import net.minecraft.world.entity.animal.horse.ZombieHorse;
import net.minecraft.world.entity.animal.nautilus.AbstractNautilus;
import net.minecraft.world.entity.animal.nautilus.ZombieNautilus;
import net.minecraft.world.entity.animal.sheep.Sheep;
import net.minecraft.world.entity.animal.sniffer.Sniffer;
import net.minecraft.world.entity.animal.wolf.Wolf;
import net.alexscaves.server.entity.living.GrottoceratopsEntity;
import net.alexscaves.server.entity.living.RelicheirusEntity;
import net.alexscaves.server.entity.living.SubterranodonEntity;
import net.alexscaves.server.entity.living.TremorsaurusEntity;
import net.alexscaves.server.entity.living.TrilocarisEntity;
import net.alexscaves.server.entity.living.VallumraptorEntity;
import net.alexsmobs.entity.EntityBlobfish;
import net.alexsmobs.entity.EntityBunfungus;
import net.alexsmobs.entity.EntityCosmicCod;
import net.alexsmobs.entity.EntityFrilledShark;
import net.alexsmobs.entity.EntityFlyingFish;
import net.alexsmobs.entity.EntityMimicOctopus;
import net.alexsmobs.entity.EntityMungus;
import net.alexsmobs.entity.EntityAlligatorSnappingTurtle;
import net.minecraft.world.entity.boss.enderdragon.EnderDragon;
import net.minecraft.world.entity.boss.wither.WitherBoss;
import net.minecraft.world.entity.decoration.ArmorStand;
import net.minecraft.world.entity.monster.AbstractSkeleton;
import net.minecraft.world.entity.monster.Blaze;
import net.minecraft.world.entity.monster.Bogged;
import net.minecraft.world.entity.monster.CaveSpider;
import net.minecraft.world.entity.monster.Creeper;
import net.minecraft.world.entity.monster.Drowned;
import net.minecraft.world.entity.monster.ElderGuardian;
import net.minecraft.world.entity.monster.EnderMan;
import net.minecraft.world.entity.monster.Endermite;
import net.minecraft.world.entity.monster.Evoker;
import net.minecraft.world.entity.monster.Ghast;
import net.minecraft.world.entity.monster.Giant;
import net.minecraft.world.entity.monster.Guardian;
import net.minecraft.world.entity.monster.Illusioner;
import net.minecraft.world.entity.monster.MagmaCube;
import net.minecraft.world.entity.monster.Monster;
import net.minecraft.world.entity.monster.Pillager;
import net.minecraft.world.entity.monster.Ravager;
import net.minecraft.world.entity.monster.Shulker;
import net.minecraft.world.entity.monster.Silverfish;
import net.minecraft.world.entity.monster.Spider;
import net.minecraft.world.entity.monster.Strider;
import net.minecraft.world.entity.monster.Vex;
import net.minecraft.world.entity.monster.Vindicator;
import net.minecraft.world.entity.monster.Witch;
import net.minecraft.world.entity.monster.Zoglin;
import net.minecraft.world.entity.monster.Zombie;
import net.minecraft.world.entity.monster.ZombifiedPiglin;
import net.minecraft.world.entity.monster.breeze.Breeze;
import net.minecraft.world.entity.monster.creaking.Creaking;
import net.minecraft.world.entity.monster.hoglin.Hoglin;
import net.minecraft.world.entity.monster.piglin.Piglin;
import net.minecraft.world.entity.monster.piglin.PiglinBrute;
import net.minecraft.world.entity.monster.warden.Warden;
import net.minecraft.world.entity.npc.Villager;
import net.minecraft.world.entity.player.Player;
import org.slf4j.Logger;

public class DefaultAttributes {
	private static final Logger LOGGER = LogUtils.getLogger();
	private static final Map<EntityType<? extends LivingEntity>, AttributeSupplier> SUPPLIERS = ImmutableMap.<EntityType<? extends LivingEntity>, AttributeSupplier>builder()
		.put(EntityType.ALLAY, Allay.createAttributes().build())
		.put(EntityType.ALLIGATOR_SNAPPING_TURTLE, EntityAlligatorSnappingTurtle.createAttributes().build())
		.put(EntityType.ANACONDA, EntityAnaconda.bakeAttributes().build())
		.put(EntityType.ANACONDA_PART, EntityAnacondaPart.bakeAttributes().build())
		.put(EntityType.ATLATITAN, AtlatitanEntity.createAttributes().build())
		.put(EntityType.ARMADILLO, Armadillo.createAttributes().build())
		.put(EntityType.ARMOR_STAND, ArmorStand.createAttributes().build())
		.put(EntityType.AXOLOTL, Axolotl.createAttributes().build())
		.put(EntityType.NAUTILUS, AbstractNautilus.createAttributes().build())
		.put(EntityType.BALD_EAGLE, EntityBaldEagle.bakeAttributes().build())
		.put(EntityType.BAT, Bat.createAttributes().build())
		.put(EntityType.BEE, Bee.createAttributes().build())
		.put(EntityType.BISON, EntityBison.bakeAttributes().build())
		.put(EntityType.CAIMAN, EntityCaiman.bakeAttributes().build())
		.put(EntityType.CAPUCHIN_MONKEY, EntityCapuchinMonkey.bakeAttributes().build())
		.put(EntityType.CAVE_CENTIPEDE_HEAD, EntityCentipedeHead.bakeAttributes().build())
		.put(EntityType.CAVE_CENTIPEDE_BODY, EntityCentipedeBody.bakeAttributes().build())
		.put(EntityType.CAVE_CENTIPEDE_TAIL, EntityCentipedeTail.bakeAttributes().build())
		.put(EntityType.BLAZE, Blaze.createAttributes().build())
		.put(EntityType.BLOBFISH, EntityBlobfish.createAttributes().build())
		.put(EntityType.BLUE_JAY, EntityBlueJay.bakeAttributes().build())
		.put(EntityType.BOGGED, Bogged.createAttributes().build())
		.put(EntityType.BUNFUNGUS, EntityBunfungus.bakeAttributes().build())
		.put(EntityType.CACHALOT_WHALE, EntityCachalotWhale.bakeAttributes().build())
		.put(EntityType.CAT, Cat.createAttributes().build())
		.put(EntityType.CATFISH, EntityCatfish.bakeAttributes().build())
		.put(EntityType.CAMEL, Camel.createAttributes().build())
		.put(EntityType.CAVE_SPIDER, CaveSpider.createCaveSpider().build())
		.put(EntityType.CHICKEN, Chicken.createAttributes().build())
		.put(EntityType.COCKROACH, EntityCockroach.bakeAttributes().build())
		.put(EntityType.COMB_JELLY, EntityCombJelly.bakeAttributes().build())
		.put(EntityType.COSMIC_COD, EntityCosmicCod.createAttributes().build())
		.put(EntityType.FRILLED_SHARK, EntityFrilledShark.createAttributes().build())
		.put(EntityType.COSMAW, EntityCosmaw.bakeAttributes().build())
		.put(EntityType.COD, AbstractFish.createAttributes().build())
		.put(EntityType.CROCODILE, EntityCrocodile.bakeAttributes().build())
		.put(EntityType.COPPER_GOLEM, CopperGolem.createAttributes().build())
		.put(EntityType.COW, Cow.createAttributes().build())
		.put(EntityType.CROW, EntityCrow.bakeAttributes().build())
		.put(EntityType.CREAKING, Creaking.createAttributes().build())
		.put(EntityType.CREEPER, Creeper.createAttributes().build())
		.put(EntityType.DOLPHIN, Dolphin.createAttributes().build())
		.put(EntityType.DONKEY, AbstractChestedHorse.createBaseChestedHorseAttributes().build())
		.put(EntityType.DROWNED, Drowned.createAttributes().build())
		.put(EntityType.ZOMBIE_NAUTILUS, ZombieNautilus.createAttributes().build())
		.put(EntityType.ELEPHANT, EntityElephant.bakeAttributes().build())
		.put(EntityType.EMU, EntityEmu.createAttributes().build())
		.put(EntityType.ELDER_GUARDIAN, ElderGuardian.createAttributes().build())
		.put(EntityType.ENDERGRADE, EntityEndergrade.bakeAttributes().build())
		.put(EntityType.ENDERIOPHAGE, EntityEnderiophage.createAttributes().build())
		.put(EntityType.ENDERMAN, EnderMan.createAttributes().build())
		.put(EntityType.ENDERMITE, Endermite.createAttributes().build())
		.put(EntityType.ENDER_DRAGON, EnderDragon.createAttributes().build())
		.put(EntityType.EVOKER, Evoker.createAttributes().build())
		.put(EntityType.BREEZE, Breeze.createAttributes().build())
		.put(EntityType.FLYING_FISH, EntityFlyingFish.createAttributes().build())
		.put(EntityType.FOX, Fox.createAttributes().build())
		.put(EntityType.FROG, Frog.createAttributes().build())
		.put(EntityType.GAZELLE, EntityGazelle.createAttributes().build())
		.put(EntityType.GELADA_MONKEY, EntityGeladaMonkey.bakeAttributes().build())
		.put(EntityType.GHAST, Ghast.createAttributes().build())
		.put(EntityType.HAPPY_GHAST, HappyGhast.createAttributes().build())
		.put(EntityType.GIANT, Giant.createAttributes().build())
		.put(EntityType.GLOW_SQUID, GlowSquid.createAttributes().build())
		.put(EntityType.GIANT_SQUID, EntityGiantSquid.createAttributes().build())
		.put(EntityType.GOAT, Goat.createAttributes().build())
		.put(EntityType.GORILLA, EntityGorilla.createAttributes().build())
		.put(EntityType.GRIZZLY_BEAR, EntityGrizzlyBear.bakeAttributes().build())
		.put(EntityType.GROTTOCERATOPS, GrottoceratopsEntity.createAttributes().build())
		.put(EntityType.GUARDIAN, Guardian.createAttributes().build())
		.put(EntityType.HAMMERHEAD_SHARK, EntityHammerheadShark.bakeAttributes().build())
		.put(EntityType.HOGLIN, Hoglin.createAttributes().build())
		.put(EntityType.HUMMINGBIRD, EntityHummingbird.bakeAttributes().build())
		.put(EntityType.HORSE, AbstractHorse.createBaseHorseAttributes().build())
		.put(EntityType.HUSK, Zombie.createAttributes().build())
		.put(EntityType.ILLUSIONER, Illusioner.createAttributes().build())
		.put(EntityType.JERBOA, EntityJerboa.bakeAttributes().build())
		.put(EntityType.KANGAROO, EntityKangaroo.bakeAttributes().build())
		.put(EntityType.KOMODO_DRAGON, EntityKomodoDragon.bakeAttributes().build())
		.put(EntityType.LEAFCUTTER_ANT, EntityLeafcutterAnt.bakeAttributes().build())
		.put(EntityType.IRON_GOLEM, IronGolem.createAttributes().build())
		.put(EntityType.LLAMA, Llama.createAttributes().build())
		.put(EntityType.LOBSTER, net.minecraft.world.entity.animal.EntityLobster.bakeAttributes().build())
		.put(EntityType.MAGMA_CUBE, MagmaCube.createAttributes().build())
		.put(EntityType.MANNEQUIN, LivingEntity.createLivingAttributes().build())
		.put(EntityType.MANTIS_SHRIMP, EntityMantisShrimp.bakeAttributes().build())
		.put(EntityType.MIMIC_OCTOPUS, EntityMimicOctopus.createAttributes().build())
		.put(EntityType.MOOSHROOM, Cow.createAttributes().build())
		.put(EntityType.MOOSE, EntityMoose.bakeAttributes().build())
		.put(EntityType.MUDSKIPPER, EntityMudskipper.createAttributes().build())
		.put(EntityType.MULE, AbstractChestedHorse.createBaseChestedHorseAttributes().build())
		.put(EntityType.MUNGUS, EntityMungus.bakeAttributes().build())
		.put(EntityType.OCELOT, Ocelot.createAttributes().build())
		.put(EntityType.ORCA, EntityOrca.createAttributes().build())
		.put(EntityType.PANDA, Panda.createAttributes().build())
		.put(EntityType.PARROT, Parrot.createAttributes().build())
		.put(EntityType.PHANTOM, Monster.createMonsterAttributes().build())
		.put(EntityType.PIG, Pig.createAttributes().build())
		.put(EntityType.PIGLIN, Piglin.createAttributes().build())
		.put(EntityType.PIGLIN_BRUTE, PiglinBrute.createAttributes().build())
		.put(EntityType.PILLAGER, Pillager.createAttributes().build())
		.put(EntityType.PLATYPUS, EntityPlatypus.bakeAttributes().build())
		.put(EntityType.PLAYER, Player.createAttributes().build())
		.put(EntityType.POLAR_BEAR, PolarBear.createAttributes().build())
		.put(EntityType.POTOO, EntityPotoo.bakeAttributes().build())
		.put(EntityType.PUFFERFISH, AbstractFish.createAttributes().build())
		.put(EntityType.RABBIT, Rabbit.createAttributes().build())
		.put(EntityType.RACCOON, EntityRaccoon.createAttributes().build())
		.put(EntityType.RAIN_FROG, EntityRainFrog.bakeAttributes().build())
		.put(EntityType.RATTLESNAKE, EntityRattlesnake.bakeAttributes().build())
		.put(EntityType.RHINOCEROS, EntityRhinoceros.createAttributes().build())
		.put(EntityType.ROADRUNNER, EntityRoadrunner.bakeAttributes().build())
		.put(EntityType.RAVAGER, Ravager.createAttributes().build())
		.put(EntityType.RELICHEIRUS, RelicheirusEntity.createAttributes().build())
		.put(EntityType.SALMON, AbstractFish.createAttributes().build())
		.put(EntityType.ANTEATER, EntityAnteater.createAttributes().build())
		.put(EntityType.MIMICUBE, EntityMimicube.createAttributes().build())
		.put(EntityType.SEAGULL, EntitySeagull.createAttributes().build())
		.put(EntityType.SHEEP, Sheep.createAttributes().build())
		.put(EntityType.SHOEBILL, EntityShoebill.bakeAttributes().build())
		.put(EntityType.SKUNK, EntitySkunk.bakeAttributes().build())
		.put(EntityType.SPECTRE, EntitySpectre.createAttributes().build())
		.put(EntityType.SUGAR_GLIDER, EntitySugarGlider.bakeAttributes().build())
		.put(EntityType.SUNBIRD, EntitySunbird.createAttributes().build())
		.put(EntityType.SHULKER, Shulker.createAttributes().build())
		.put(EntityType.SILVERFISH, Silverfish.createAttributes().build())
		.put(EntityType.SKELETON, AbstractSkeleton.createAttributes().build())
		.put(EntityType.SKELEWAG, EntitySkelewag.createAttributes().build())
		.put(EntityType.SKELETON_HORSE, SkeletonHorse.createAttributes().build())
		.put(EntityType.SLIME, Monster.createMonsterAttributes().build())
		.put(EntityType.SNIFFER, Sniffer.createAttributes().build())
		.put(EntityType.SUBTERRANODON, SubterranodonEntity.createAttributes().build())
		.put(EntityType.TREMORSAURUS, TremorsaurusEntity.createAttributes().build())
		.put(EntityType.TRILOCARIS, TrilocarisEntity.createAttributes().build())
		.put(EntityType.TOUCAN, EntityToucan.bakeAttributes().build())
		.put(EntityType.TARANTULA_HAWK, EntityTarantulaHawk.bakeAttributes().build())
		.put(EntityType.TASMANIAN_DEVIL, EntityTasmanianDevil.bakeAttributes().build())
		.put(EntityType.TIGER, EntityTiger.bakeAttributes().build())
		.put(EntityType.UNDERMINER, EntityUnderminer.bakeAttributes().build())
		.put(EntityType.WARPED_TOAD, EntityWarpedToad.bakeAttributes().build())
		.put(EntityType.VALLUMRAPTOR, VallumraptorEntity.createAttributes().build())
		.put(EntityType.SNOW_GOLEM, SnowGolem.createAttributes().build())
		.put(EntityType.SNOW_LEOPARD, EntitySnowLeopard.createAttributes().build())
		.put(EntityType.SPIDER, Spider.createAttributes().build())
		.put(EntityType.SQUID, Squid.createAttributes().build())
		.put(EntityType.STRAY, AbstractSkeleton.createAttributes().build())
		.put(EntityType.STRIDER, Strider.createAttributes().build())
		.put(EntityType.TADPOLE, Tadpole.createAttributes().build())
		.put(EntityType.TRADER_LLAMA, Llama.createAttributes().build())
		.put(EntityType.TROPICAL_FISH, AbstractFish.createAttributes().build())
		.put(EntityType.TURTLE, Turtle.createAttributes().build())
		.put(EntityType.TERRAPIN, EntityTerrapin.bakeAttributes().build())
		.put(EntityType.VEX, Vex.createAttributes().build())
		.put(EntityType.VILLAGER, Villager.createAttributes().build())
		.put(EntityType.VINDICATOR, Vindicator.createAttributes().build())
		.put(EntityType.WARDEN, Warden.createAttributes().build())
		.put(EntityType.WANDERING_TRADER, Mob.createMobAttributes().build())
		.put(EntityType.WITCH, Witch.createAttributes().build())
		.put(EntityType.WITHER, WitherBoss.createAttributes().build())
		.put(EntityType.WITHER_SKELETON, AbstractSkeleton.createAttributes().build())
		.put(EntityType.WOLF, Wolf.createAttributes().build())
		.put(EntityType.ZOGLIN, Zoglin.createAttributes().build())
		.put(EntityType.ZOMBIE, Zombie.createAttributes().build())
		.put(EntityType.ZOMBIE_HORSE, ZombieHorse.createAttributes().build())
		.put(EntityType.ZOMBIE_VILLAGER, Zombie.createAttributes().build())
		.put(EntityType.ZOMBIFIED_PIGLIN, ZombifiedPiglin.createAttributes().build())
		.build();

	public static AttributeSupplier getSupplier(EntityType<? extends LivingEntity> entityType) {
		return (AttributeSupplier)SUPPLIERS.get(entityType);
	}

	public static boolean hasSupplier(EntityType<?> entityType) {
		return SUPPLIERS.containsKey(entityType);
	}

	public static void validate() {
		BuiltInRegistries.ENTITY_TYPE
			.stream()
			.filter(entityType -> entityType.getCategory() != MobCategory.MISC)
			.filter(entityType -> !hasSupplier(entityType))
			.map(BuiltInRegistries.ENTITY_TYPE::getKey)
			.forEach(resourceLocation -> Util.logAndPauseIfInIde("Entity " + resourceLocation + " has no attributes"));
	}
}
