package net.caffeinemc.mods.sodium.mixin.core.render.world;

import net.minecraft.world.entity.Entity;
import net.minecraft.world.phys.AABB;

/**
 * Compile-time stub for Sodium mixin accessor.
 * At runtime, this is generated by Sodium's mixin system.
 */
public interface EntityRendererAccessor {
    AABB getCullingBox(Entity entity);
}
