package net.caffeinemc.mods.sodium.mixin.core.render.texture;

/**
 * Compile-time stub for Sodium mixin accessor.
 * At runtime, this is generated by Sodium's mixin system.
 */
public interface TextureAtlasAccessor {
    int getWidth();
    int getHeight();
}
