//! The whole-frame submit request, its result and profile snapshot.

use super::*;

#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct FfiWholeFrameSubmitRequest {
    pub header: FfiHeader,
    pub generation: u64,
    pub frame_id: u64,
    pub correlation_id: u64,
    pub frame_target: FfiHandle,
    pub gui_width: i32,
    pub gui_height: i32,
    pub viewport_width: i32,
    pub viewport_height: i32,
    pub view_matrix: [f32; 16],
    pub projection_matrix: [f32; 16],
    pub world_background: FfiWorldBackgroundRequest,
    pub world_segments: FfiSlice<FfiWorldLineSegmentRequest>,
    pub world_crack_quads: FfiSlice<FfiWorldCrackQuadRequest>,
    pub world_border_quads: FfiSlice<FfiWorldBorderQuadRequest>,
    pub world_material_quads: FfiSlice<FfiWorldMaterialQuadRequest>,
    pub world_material_table: FfiSlice<FfiWorldMaterialTableRecord>,
    pub world_material_compact_quads: FfiSlice<FfiWorldMaterialCompactQuadRequest>,
    pub world_mesh_instances: FfiSlice<FfiWorldMeshInstanceRecord>,
    pub gui_sprites: FfiSlice<FfiGuiSpriteRequest>,
    pub gui_affine_quads: FfiSlice<FfiGuiAffineQuadRequest>,
    pub negotiated_feature_bits: u64,
    pub voxel_volume_frame: FfiWorldVoxelVolumeFrame,
    pub shader_environment_frame: FfiWorldShaderEnvironmentFrame,
    pub world_lod_instances: FfiSlice<FfiWorldLodColumnInstanceRecord>,
    pub world_lod_render_frame: FfiWorldLodRenderFrame,
    pub world_feature_coverage: FfiWorldFeatureCoverage,
    /// Appended in ABI v20. The stream is semantic only and is consumed by
    /// the Rust-owned world-text pass; Java text draw state never crosses this
    /// boundary.
    pub world_text_quads: FfiSlice<FfiWorldTextQuadRequest>,
    /// Appended so legacy whole-frame field offsets remain stable. The mesh
    /// batch is consumed by the Rust-owned GUI mesh frontend.
    pub gui_mesh_batches: FfiSlice<FfiGuiMeshBatchRequest>,
    /// Appended in ABI v21. The enabled record selects the Rust-owned hand
    /// projection and fresh depth domain; disabled is the explicit semantic
    /// value for frames without first-person work.
    pub world_first_person_frame: FfiWorldFirstPersonFrame,
    /// Appended in ABI v22. These copied mesh references share the existing
    /// asset/cache contract, but are intentionally distinct from camera-space
    /// world instances. When the hand record is enabled they are consumed by
    /// the dedicated Rust first-person pass, never batched into the world.
    pub world_first_person_mesh_instances: FfiSlice<FfiWorldMeshInstanceRecord>,
    /// Appended in ABI v23. `-1` means no GUI blur boundary; a non-negative
    /// value identifies the source GUI stratum before which blur is requested.
    /// The request is consumed by the Rust-owned blur graph; selected source
    /// and normal-world composition both retain the same semantic boundary.
    pub gui_blur_before_stratum: i32,
    /// Appended in ABI v24. The vanilla menu-background blur radius in bounded
    /// semantic pixels; ignored when `gui_blur_before_stratum` is `-1`.
    pub gui_blur_radius: i32,
    /// Appended in ABI v25. Optional copied semantic post-effect identity;
    /// Rust resolves the definition and shader stages from its own matching
    /// shader-pack snapshots. Java post-chain objects and backend handles are
    /// never transported.
    pub post_effect_id: FfiBytes,
    pub gui_projection_width: f32,
    pub gui_projection_height: f32,
    pub gui_tiled_quads: FfiSlice<FfiGuiTiledQuadRequest>,
    /// ABI v32: immutable engine inputs, never the Java Globals GPU buffer.
    pub engine_globals_present: u32,
    pub engine_screen_width: u32,
    pub engine_screen_height: u32,
    pub engine_game_ticks: i64,
    pub engine_partial_tick: f32,
    pub engine_glint_alpha: f32,
    pub engine_menu_blur_radius: i32,
    /// ABI v50: ordinary particle semantics; no Java-expanded vertices.
    pub world_particle_quads: FfiSlice<FfiWorldParticleQuadRequest>,
    pub world_experience_orbs: FfiSlice<FfiWorldExperienceOrbInstanceRecord>,
    /// ABI v65: compact DH generic boxes. Rust expands the six semantic faces
    /// into its cached material-instance topology; Java never constructs a
    /// per-face vertex record for this stream.
    pub world_distant_horizons_generic_boxes: FfiSlice<FfiWorldDistantHorizonsGenericBoxRecord>,
    /// ABI v69: off-camera static-terrain shadow casters and the frame's
    /// full-precision terrain camera (required only when casters are present).
    pub world_static_terrain_shadow_casters: FfiSlice<FfiStaticTerrainShadowCaster>,
    pub static_terrain_camera: [f64; 3],
    /// ABI v70: camera-visible static-terrain section layers, in draw order
    /// (translucent back to front), placed with `static_terrain_camera`.
    pub world_static_terrain_sections: FfiSlice<FfiStaticTerrainSection>,
    /// ABI v71: raw part poses of the frame's model-rig instances; Rust
    /// composes each rig's hierarchy and expands its part instances.
    pub world_model_rig_poses: FfiSlice<FfiModelRigPose>,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct FfiWholeFrameSubmitResult {
    pub header: FfiHeader,
    pub status: i32,
    pub error_domain: u32,
    pub submission_id: u64,
    pub world_segment_count: u64,
    pub world_vertex_count: u64,
    pub world_batch_count: u64,
    pub world_draw_count: u64,
    pub world_crack_quad_count: u64,
    pub world_crack_batch_count: u64,
    pub world_crack_draw_count: u64,
    pub world_border_quad_count: u64,
    pub world_border_batch_count: u64,
    pub world_border_draw_count: u64,
    pub world_material_quad_count: u64,
    pub world_material_batch_count: u64,
    pub world_material_draw_count: u64,
    pub world_mesh_instance_count: u64,
    pub world_mesh_batch_count: u64,
    pub world_mesh_draw_count: u64,
    pub world_background_clear_count: u64,
    pub world_background_diagnostic_fallback_count: u64,
    pub world_background_sky_type: u64,
    pub world_background_color_argb: u64,
    pub depth_attachment_creates: u64,
    pub depth_attachment_reuses: u64,
    pub depth_attachment_retires: u64,
    pub outline_cache_hits: u64,
    pub outline_cache_misses: u64,
    pub crack_cache_hits: u64,
    pub crack_cache_misses: u64,
    pub border_cache_hits: u64,
    pub border_cache_misses: u64,
    pub material_cache_hits: u64,
    pub material_cache_misses: u64,
    pub mesh_cache_hits: u64,
    pub mesh_cache_misses: u64,
    pub sprite_count: u64,
    pub sprite_batch_count: u64,
    pub gui_mesh_item_count: u64,
    pub gui_mesh_batch_count: u64,
    pub gui_mesh_draw_count: u64,
    pub gui_entity_preview_item_count: u64,
    pub gui_entity_preview_batch_count: u64,
    pub gui_entity_preview_draw_count: u64,
    pub gui_entity_preview_material_mask: u64,
    pub gui_entity_preview_vertex_count: u64,
    pub gui_entity_preview_index_count: u64,
    pub cache_hits: u64,
    pub cache_misses: u64,
    pub resource_creates: u64,
    pub command_lists: u64,
    pub command_ops: u64,
    pub metrics: FfiMetricsSnapshot,
    pub profile: FfiWholeFrameProfileSnapshot,
}

#[repr(C)]
#[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
pub struct FfiWholeFrameProfileSnapshot {
    pub ffi_decode_nanos: u64,
    pub gui_frontend_nanos: u64,
    pub world_frontend_total_nanos: u64,
    pub world_validate_frame_nanos: u64,
    pub world_batching_nanos: u64,
    pub world_resource_prepare_nanos: u64,
    pub world_prepare_target_query_nanos: u64,
    pub world_prepare_render_resources_nanos: u64,
    pub world_prepare_depth_attachment_nanos: u64,
    pub world_prepare_g_buffer_resources_nanos: u64,
    pub world_prepare_g_buffer_cache_check_nanos: u64,
    pub world_prepare_g_buffer_destroy_nanos: u64,
    pub world_prepare_g_buffer_plan_nanos: u64,
    pub world_prepare_g_buffer_create_nanos: u64,
    pub world_prepare_frame_pass_nanos: u64,
    pub world_mesh_section_expand_group_nanos: u64,
    pub shader_plan_lookup_nanos: u64,
    pub gal_command_generation_nanos: u64,
    pub gal_submit_total_nanos: u64,
    pub gal_validate_ops_nanos: u64,
    pub gal_validate_handles_nanos: u64,
    pub gal_hazard_analysis_nanos: u64,
    pub backend_encode_nanos: u64,
    pub backend_submit_nanos: u64,
    pub backend_retire_nanos: u64,
    pub vulkan_command_buffer_alloc_nanos: u64,
    pub vulkan_command_buffer_begin_nanos: u64,
    pub vulkan_command_recording_nanos: u64,
    pub vulkan_command_buffer_end_nanos: u64,
    pub vulkan_queue_submit_nanos: u64,
    pub vulkan_timeline_poll_nanos: u64,
    pub vulkan_timeline_wait_nanos: u64,
    pub vulkan_device_wait_idle_nanos: u64,
    pub vulkan_command_buffers_allocated: u64,
    pub vulkan_command_buffers_freed: u64,
    pub vulkan_wait_count: u64,
    pub vulkan_device_wait_idle_count: u64,
    pub resource_creates_delta: u64,
    pub resource_destroys_delta: u64,
    pub host_write_ops: u64,
    pub host_write_bytes: u64,
    pub barrier_ops: u64,
    pub pass_count: u64,
    pub draw_ops: u64,
    pub draw_indexed_ops: u64,
    pub pipeline_binds: u64,
    pub resource_set_binds: u64,
    pub gpu_timestamp_status: u64,
    pub gpu_shadow_depth_nanos: u64,
    pub gpu_terrain_opaque_nanos: u64,
    pub gpu_terrain_cutout_nanos: u64,
    pub gpu_deferred_lighting_nanos: u64,
    pub gpu_composite0_nanos: u64,
    pub gpu_composite1_nanos: u64,
    pub gpu_final_output_nanos: u64,
    pub gpu_frame_total_nanos: u64,
    pub g_buffer_persistent_cache_hits: u64,
    pub g_buffer_persistent_cache_misses: u64,
    pub g_buffer_final_binding_cache_hits: u64,
    pub g_buffer_final_binding_cache_misses: u64,
    pub g_buffer_attachment_creates: u64,
    pub g_buffer_pipeline_creates: u64,
    pub g_buffer_shader_module_creates: u64,
    pub g_buffer_descriptor_creates: u64,
    pub g_buffer_render_target_creates: u64,
    pub g_buffer_resources_retired: u64,
    pub world_prepare_g_buffer_persistent_key_nanos: u64,
    pub world_prepare_g_buffer_persistent_lookup_nanos: u64,
    pub world_prepare_g_buffer_final_key_nanos: u64,
    pub world_prepare_g_buffer_final_lookup_nanos: u64,
    pub world_prepare_g_buffer_final_create_nanos: u64,
    pub world_prepare_frame_target_attachment_query_nanos: u64,
    pub world_prepare_mesh_material_asset_nanos: u64,
    pub world_prepare_metrics_accounting_nanos: u64,
    pub g_buffer_final_pass_creates: u64,
    pub vulkan_acquire_nanos: u64,
    pub vulkan_present_nanos: u64,
    pub vulkan_present_wait_nanos: u64,
    pub vulkan_present_mode: u64,
    pub vulkan_requested_present_mode: u64,
    pub vulkan_supported_present_modes: u64,
    pub vulkan_present_mode_fallback_reason: u64,
    pub vulkan_acquired_image_index: u64,
    pub vulkan_swapchain_generation: u64,
    pub vulkan_swapchain_image_count: u64,
    pub vulkan_surface_min_image_count: u64,
    pub vulkan_surface_max_image_count: u64,
    pub vulkan_configured_frames_in_flight: u64,
    pub vulkan_images_in_flight: u64,
    pub vulkan_available_frame_slots: u64,
    pub gal_hazard_read_events: u64,
    pub gal_hazard_write_events: u64,
    pub gal_hazard_candidates_examined: u64,
    pub gal_hazard_conflicts: u64,
    pub gal_hazard_barriers_applied: u64,
    pub gal_hazard_active_read_entries: u64,
    pub gal_hazard_active_write_entries: u64,
    pub gal_command_ops_before_normalize: u64,
    pub gal_command_ops_after_normalize: u64,
    pub gal_redundant_pipeline_binds_removed: u64,
    pub gal_redundant_resource_set_binds_removed: u64,
    pub gal_redundant_vertex_buffer_binds_removed: u64,
    pub gal_redundant_index_buffer_binds_removed: u64,
    pub world_prepare_mesh_cache_scan_nanos: u64,
    pub world_prepare_material_resource_nanos: u64,
    pub world_prepare_mesh_stream_capacity_nanos: u64,
    pub world_prepare_mesh_stream_lookup_nanos: u64,
    pub world_prepare_mesh_stream_grow_nanos: u64,
    pub world_prepare_mesh_resource_nanos: u64,
    pub world_prepare_material_slot_check_nanos: u64,
    pub world_prepare_mesh_slot_check_nanos: u64,
    pub world_prepare_mesh_batch_count: u64,
    pub world_prepare_mesh_stream_required_bytes: u64,
    pub world_prepare_mesh_stream_capacity_bytes: u64,
    pub world_prepare_mesh_stream_grows: u64,
    pub world_mesh_stream_payload_pack_nanos: u64,
    pub world_mesh_draw_record_nanos: u64,
    pub world_mesh_stream_payload_bytes: u64,
    pub world_mesh_dynamic_offset_count: u64,
    pub gui_mesh_prepare_nanos: u64,
    pub gui_mesh_lower_nanos: u64,
    pub gpu_distant_horizons_opaque_nanos: u64,
    pub world_mesh_page_indirect_batch_count: u64,
    pub world_mesh_page_indirect_run_count: u64,
    pub world_mesh_dynamic_terrain_batch_count: u64,
    pub world_mesh_dynamic_non_terrain_batch_count: u64,
    pub world_mesh_terrain_translucent_batch_count: u64,
    pub whole_frame_native_total_nanos: u64,
    pub world_post_submit_confirm_nanos: u64,
    pub gal_command_recording_finish_nanos: u64,
    pub gal_command_recording_deferred_destroys: u64,
}

impl Default for FfiWholeFrameSubmitResult {
    fn default() -> Self {
        Self {
            header: FfiHeader {
                version: FFI_ABI_VERSION,
                byte_size: size_of::<Self>() as u32,
            },
            status: StatusCode::Ok as i32,
            error_domain: 0,
            submission_id: 0,
            world_segment_count: 0,
            world_vertex_count: 0,
            world_batch_count: 0,
            world_draw_count: 0,
            world_crack_quad_count: 0,
            world_crack_batch_count: 0,
            world_crack_draw_count: 0,
            world_border_quad_count: 0,
            world_border_batch_count: 0,
            world_border_draw_count: 0,
            world_material_quad_count: 0,
            world_material_batch_count: 0,
            world_material_draw_count: 0,
            world_mesh_instance_count: 0,
            world_mesh_batch_count: 0,
            world_mesh_draw_count: 0,
            world_background_clear_count: 0,
            world_background_diagnostic_fallback_count: 0,
            world_background_sky_type: 0,
            world_background_color_argb: 0,
            depth_attachment_creates: 0,
            depth_attachment_reuses: 0,
            depth_attachment_retires: 0,
            outline_cache_hits: 0,
            outline_cache_misses: 0,
            crack_cache_hits: 0,
            crack_cache_misses: 0,
            border_cache_hits: 0,
            border_cache_misses: 0,
            material_cache_hits: 0,
            material_cache_misses: 0,
            mesh_cache_hits: 0,
            mesh_cache_misses: 0,
            sprite_count: 0,
            sprite_batch_count: 0,
            gui_mesh_item_count: 0,
            gui_mesh_batch_count: 0,
            gui_mesh_draw_count: 0,
            gui_entity_preview_item_count: 0,
            gui_entity_preview_batch_count: 0,
            gui_entity_preview_draw_count: 0,
            gui_entity_preview_material_mask: 0,
            gui_entity_preview_vertex_count: 0,
            gui_entity_preview_index_count: 0,
            cache_hits: 0,
            cache_misses: 0,
            resource_creates: 0,
            command_lists: 0,
            command_ops: 0,
            metrics: FfiMetricsSnapshot::default(),
            profile: FfiWholeFrameProfileSnapshot::default(),
        }
    }
}
