//! State-only sound policy and shared note/offset configuration.
use crate::content::{property::Builtin, sound::{SoundType, Instrument}, block::offset::Profile};
#[derive(Clone, Copy)]
pub(super) enum SoundRule { Constant(SoundType), DecoratedPot, PewenBranch }
pub struct Material {
    pub base_sound: SoundType,
    sound: SoundRule,
    pub instrument: Instrument,
    pub offset: Profile,
}
impl Material {
    pub(super) fn sound(&self, properties: &[Builtin], indices: &[i32]) -> SoundType {
        let boolean = |p: Builtin| {
            let slot = properties.iter().position(|&v| v == p).expect("sound rule property");
            p.domain().boolean(indices[slot] as u16).expect("sound rule boolean")
        };
        match self.sound {
            SoundRule::Constant(sound) => sound,
            SoundRule::DecoratedPot => if boolean(Builtin::Cracked) {SoundType::DecoratedPotCracked} else {SoundType::DecoratedPot},
            SoundRule::PewenBranch => if boolean(Builtin::PewenBranchBlockPines) {SoundType::Grass} else {self.base_sound},
        }
    }
}
macro_rules! materials {
    ($($name:ident => $value:expr),+ $(,)?) => {
        #[derive(Clone, Copy)]
        #[repr(u16)]
        pub(super) enum MaterialSet { $($name),+ }
        pub(super) static PROFILES: &[Material] = &[$($value),+];
    };
}
materials! {
    Air => Material { base_sound: SoundType::Stone, sound: SoundRule::Constant(SoundType::Stone), instrument: Instrument::Harp, offset: Profile::Air },
    Stone => Material { base_sound: SoundType::Stone, sound: SoundRule::Constant(SoundType::Stone), instrument: Instrument::Basedrum, offset: Profile::Air },
    Limestone => Material { base_sound: SoundType::DripstoneBlock, sound: SoundRule::Constant(SoundType::DripstoneBlock), instrument: Instrument::Basedrum, offset: Profile::Air },
    GrassBlock => Material { base_sound: SoundType::Grass, sound: SoundRule::Constant(SoundType::Grass), instrument: Instrument::Harp, offset: Profile::Air },
    Dirt => Material { base_sound: SoundType::Gravel, sound: SoundRule::Constant(SoundType::Gravel), instrument: Instrument::Harp, offset: Profile::Air },
    OakPlanks => Material { base_sound: SoundType::Wood, sound: SoundRule::Constant(SoundType::Wood), instrument: Instrument::Bass, offset: Profile::Air },
    CherryPlanks => Material { base_sound: SoundType::CherryWood, sound: SoundRule::Constant(SoundType::CherryWood), instrument: Instrument::Bass, offset: Profile::Air },
    BambooPlanks => Material { base_sound: SoundType::BambooWood, sound: SoundRule::Constant(SoundType::BambooWood), instrument: Instrument::Bass, offset: Profile::Air },
    CherrySapling => Material { base_sound: SoundType::CherrySapling, sound: SoundRule::Constant(SoundType::CherrySapling), instrument: Instrument::Harp, offset: Profile::Air },
    MangrovePropagule => Material { base_sound: SoundType::Grass, sound: SoundRule::Constant(SoundType::Grass), instrument: Instrument::Harp, offset: Profile::MangrovePropagule },
    Water => Material { base_sound: SoundType::Empty, sound: SoundRule::Constant(SoundType::Empty), instrument: Instrument::Harp, offset: Profile::Air },
    Sand => Material { base_sound: SoundType::Sand, sound: SoundRule::Constant(SoundType::Sand), instrument: Instrument::Snare, offset: Profile::Air },
    SuspiciousSand => Material { base_sound: SoundType::SuspiciousSand, sound: SoundRule::Constant(SoundType::SuspiciousSand), instrument: Instrument::Snare, offset: Profile::Air },
    Gravel => Material { base_sound: SoundType::Gravel, sound: SoundRule::Constant(SoundType::Gravel), instrument: Instrument::Snare, offset: Profile::Air },
    SuspiciousGravel => Material { base_sound: SoundType::SuspiciousGravel, sound: SoundRule::Constant(SoundType::SuspiciousGravel), instrument: Instrument::Snare, offset: Profile::Air },
    DeepslateGoldOre => Material { base_sound: SoundType::Deepslate, sound: SoundRule::Constant(SoundType::Deepslate), instrument: Instrument::Basedrum, offset: Profile::Air },
    NetherGoldOre => Material { base_sound: SoundType::NetherGoldOre, sound: SoundRule::Constant(SoundType::NetherGoldOre), instrument: Instrument::Basedrum, offset: Profile::Air },
    MangroveRoots => Material { base_sound: SoundType::MangroveRoots, sound: SoundRule::Constant(SoundType::MangroveRoots), instrument: Instrument::Bass, offset: Profile::Air },
    MuddyMangroveRoots => Material { base_sound: SoundType::MuddyMangroveRoots, sound: SoundRule::Constant(SoundType::MuddyMangroveRoots), instrument: Instrument::Harp, offset: Profile::Air },
    CherryLeaves => Material { base_sound: SoundType::CherryLeaves, sound: SoundRule::Constant(SoundType::CherryLeaves), instrument: Instrument::Harp, offset: Profile::Air },
    AzaleaLeaves => Material { base_sound: SoundType::AzaleaLeaves, sound: SoundRule::Constant(SoundType::AzaleaLeaves), instrument: Instrument::Harp, offset: Profile::Air },
    Sponge => Material { base_sound: SoundType::Sponge, sound: SoundRule::Constant(SoundType::Sponge), instrument: Instrument::Harp, offset: Profile::Air },
    WetSponge => Material { base_sound: SoundType::WetSponge, sound: SoundRule::Constant(SoundType::WetSponge), instrument: Instrument::Harp, offset: Profile::Air },
    Glass => Material { base_sound: SoundType::Glass, sound: SoundRule::Constant(SoundType::Glass), instrument: Instrument::Hat, offset: Profile::Air },
    WhiteBed => Material { base_sound: SoundType::Wood, sound: SoundRule::Constant(SoundType::Wood), instrument: Instrument::Harp, offset: Profile::Air },
    PoweredRail => Material { base_sound: SoundType::Metal, sound: SoundRule::Constant(SoundType::Metal), instrument: Instrument::Harp, offset: Profile::Air },
    Cobweb => Material { base_sound: SoundType::Cobweb, sound: SoundRule::Constant(SoundType::Cobweb), instrument: Instrument::Harp, offset: Profile::Air },
    ShortGrass => Material { base_sound: SoundType::Grass, sound: SoundRule::Constant(SoundType::Grass), instrument: Instrument::Harp, offset: Profile::ShortGrass },
    Flytrap => Material { base_sound: SoundType::Roots, sound: SoundRule::Constant(SoundType::Roots), instrument: Instrument::Harp, offset: Profile::MangrovePropagule },
    Cycad => Material { base_sound: SoundType::Wood, sound: SoundRule::Constant(SoundType::Wood), instrument: Instrument::Harp, offset: Profile::Cycad },
    Seagrass => Material { base_sound: SoundType::WetGrass, sound: SoundRule::Constant(SoundType::WetGrass), instrument: Instrument::Harp, offset: Profile::Air },
    TallSeagrass => Material { base_sound: SoundType::WetGrass, sound: SoundRule::Constant(SoundType::WetGrass), instrument: Instrument::Harp, offset: Profile::MangrovePropagule },
    WhiteWool => Material { base_sound: SoundType::Wool, sound: SoundRule::Constant(SoundType::Wool), instrument: Instrument::Guitar, offset: Profile::Air },
    GoldBlock => Material { base_sound: SoundType::Metal, sound: SoundRule::Constant(SoundType::Metal), instrument: Instrument::Bell, offset: Profile::Air },
    IronBlock => Material { base_sound: SoundType::Iron, sound: SoundRule::Constant(SoundType::Iron), instrument: Instrument::IronXylophone, offset: Profile::Air },
    ChiseledBookshelf => Material { base_sound: SoundType::ChiseledBookshelf, sound: SoundRule::Constant(SoundType::ChiseledBookshelf), instrument: Instrument::Bass, offset: Profile::Air },
    AcaciaShelf => Material { base_sound: SoundType::Shelf, sound: SoundRule::Constant(SoundType::Shelf), instrument: Instrument::Bass, offset: Profile::Air },
    Fire => Material { base_sound: SoundType::Wool, sound: SoundRule::Constant(SoundType::Wool), instrument: Instrument::Harp, offset: Profile::Air },
    Spawner => Material { base_sound: SoundType::Spawner, sound: SoundRule::Constant(SoundType::Spawner), instrument: Instrument::Basedrum, offset: Profile::Air },
    CreakingHeart => Material { base_sound: SoundType::CreakingHeart, sound: SoundRule::Constant(SoundType::CreakingHeart), instrument: Instrument::Basedrum, offset: Profile::Air },
    Wheat => Material { base_sound: SoundType::Crop, sound: SoundRule::Constant(SoundType::Crop), instrument: Instrument::Harp, offset: Profile::Air },
    Ladder => Material { base_sound: SoundType::Ladder, sound: SoundRule::Constant(SoundType::Ladder), instrument: Instrument::Harp, offset: Profile::Air },
    OakHangingSign => Material { base_sound: SoundType::HangingSign, sound: SoundRule::Constant(SoundType::HangingSign), instrument: Instrument::Bass, offset: Profile::Air },
    CherryHangingSign => Material { base_sound: SoundType::CherryWoodHangingSign, sound: SoundRule::Constant(SoundType::CherryWoodHangingSign), instrument: Instrument::Bass, offset: Profile::Air },
    CrimsonHangingSign => Material { base_sound: SoundType::NetherWoodHangingSign, sound: SoundRule::Constant(SoundType::NetherWoodHangingSign), instrument: Instrument::Bass, offset: Profile::Air },
    BambooHangingSign => Material { base_sound: SoundType::BambooWoodHangingSign, sound: SoundRule::Constant(SoundType::BambooWoodHangingSign), instrument: Instrument::Bass, offset: Profile::Air },
    IronDoor => Material { base_sound: SoundType::Iron, sound: SoundRule::Constant(SoundType::Iron), instrument: Instrument::Harp, offset: Profile::Air },
    Snow => Material { base_sound: SoundType::Snow, sound: SoundRule::Constant(SoundType::Snow), instrument: Instrument::Harp, offset: Profile::Air },
    Ice => Material { base_sound: SoundType::Glass, sound: SoundRule::Constant(SoundType::Glass), instrument: Instrument::Harp, offset: Profile::Air },
    CactusFlower => Material { base_sound: SoundType::CactusFlower, sound: SoundRule::Constant(SoundType::CactusFlower), instrument: Instrument::Harp, offset: Profile::Air },
    Clay => Material { base_sound: SoundType::Gravel, sound: SoundRule::Constant(SoundType::Gravel), instrument: Instrument::Flute, offset: Profile::Air },
    Netherrack => Material { base_sound: SoundType::Netherrack, sound: SoundRule::Constant(SoundType::Netherrack), instrument: Instrument::Basedrum, offset: Profile::Air },
    SoulSand => Material { base_sound: SoundType::SoulSand, sound: SoundRule::Constant(SoundType::SoulSand), instrument: Instrument::CowBell, offset: Profile::Air },
    SoulSoil => Material { base_sound: SoundType::SoulSoil, sound: SoundRule::Constant(SoundType::SoulSoil), instrument: Instrument::Harp, offset: Profile::Air },
    Basalt => Material { base_sound: SoundType::Basalt, sound: SoundRule::Constant(SoundType::Basalt), instrument: Instrument::Basedrum, offset: Profile::Air },
    Glowstone => Material { base_sound: SoundType::Glass, sound: SoundRule::Constant(SoundType::Glass), instrument: Instrument::Pling, offset: Profile::Air },
    DinosaurChop => Material { base_sound: SoundType::Candle, sound: SoundRule::Constant(SoundType::Candle), instrument: Instrument::Harp, offset: Profile::Air },
    PackedMud => Material { base_sound: SoundType::PackedMud, sound: SoundRule::Constant(SoundType::PackedMud), instrument: Instrument::Harp, offset: Profile::Air },
    MudBricks => Material { base_sound: SoundType::MudBricks, sound: SoundRule::Constant(SoundType::MudBricks), instrument: Instrument::Basedrum, offset: Profile::Air },
    CopperBars => Material { base_sound: SoundType::Copper, sound: SoundRule::Constant(SoundType::Copper), instrument: Instrument::Harp, offset: Profile::Air },
    IronChain => Material { base_sound: SoundType::Chain, sound: SoundRule::Constant(SoundType::Chain), instrument: Instrument::Harp, offset: Profile::Air },
    Pumpkin => Material { base_sound: SoundType::Wood, sound: SoundRule::Constant(SoundType::Wood), instrument: Instrument::Didgeridoo, offset: Profile::Air },
    PumpkinStem => Material { base_sound: SoundType::HardCrop, sound: SoundRule::Constant(SoundType::HardCrop), instrument: Instrument::Harp, offset: Profile::Air },
    Vine => Material { base_sound: SoundType::Vine, sound: SoundRule::Constant(SoundType::Vine), instrument: Instrument::Harp, offset: Profile::Air },
    GlowLichen => Material { base_sound: SoundType::GlowLichen, sound: SoundRule::Constant(SoundType::GlowLichen), instrument: Instrument::Harp, offset: Profile::Air },
    SkunkSpray => Material { base_sound: SoundType::Frogspawn, sound: SoundRule::Constant(SoundType::Frogspawn), instrument: Instrument::Harp, offset: Profile::Air },
    ResinClump => Material { base_sound: SoundType::Resin, sound: SoundRule::Constant(SoundType::Resin), instrument: Instrument::Harp, offset: Profile::Air },
    LilyPad => Material { base_sound: SoundType::LilyPad, sound: SoundRule::Constant(SoundType::LilyPad), instrument: Instrument::Harp, offset: Profile::Air },
    ResinBlock => Material { base_sound: SoundType::Resin, sound: SoundRule::Constant(SoundType::Resin), instrument: Instrument::Basedrum, offset: Profile::Air },
    ResinBricks => Material { base_sound: SoundType::ResinBricks, sound: SoundRule::Constant(SoundType::ResinBricks), instrument: Instrument::Basedrum, offset: Profile::Air },
    NetherBricks => Material { base_sound: SoundType::NetherBricks, sound: SoundRule::Constant(SoundType::NetherBricks), instrument: Instrument::Basedrum, offset: Profile::Air },
    NetherWart => Material { base_sound: SoundType::NetherWart, sound: SoundRule::Constant(SoundType::NetherWart), instrument: Instrument::Harp, offset: Profile::Air },
    EndPortalFrame => Material { base_sound: SoundType::Glass, sound: SoundRule::Constant(SoundType::Glass), instrument: Instrument::Basedrum, offset: Profile::Air },
    EmeraldBlock => Material { base_sound: SoundType::Metal, sound: SoundRule::Constant(SoundType::Metal), instrument: Instrument::Bit, offset: Profile::Air },
    Beacon => Material { base_sound: SoundType::Stone, sound: SoundRule::Constant(SoundType::Stone), instrument: Instrument::Hat, offset: Profile::Air },
    CherryButton => Material { base_sound: SoundType::CherryWood, sound: SoundRule::Constant(SoundType::CherryWood), instrument: Instrument::Harp, offset: Profile::Air },
    BambooButton => Material { base_sound: SoundType::BambooWood, sound: SoundRule::Constant(SoundType::BambooWood), instrument: Instrument::Harp, offset: Profile::Air },
    SkeletonSkull => Material { base_sound: SoundType::Stone, sound: SoundRule::Constant(SoundType::Stone), instrument: Instrument::Skeleton, offset: Profile::Air },
    WitherSkeletonSkull => Material { base_sound: SoundType::Stone, sound: SoundRule::Constant(SoundType::Stone), instrument: Instrument::WitherSkeleton, offset: Profile::Air },
    ZombieHead => Material { base_sound: SoundType::Stone, sound: SoundRule::Constant(SoundType::Stone), instrument: Instrument::Zombie, offset: Profile::Air },
    PlayerHead => Material { base_sound: SoundType::Stone, sound: SoundRule::Constant(SoundType::Stone), instrument: Instrument::CustomHead, offset: Profile::Air },
    CreeperHead => Material { base_sound: SoundType::Stone, sound: SoundRule::Constant(SoundType::Stone), instrument: Instrument::Creeper, offset: Profile::Air },
    DragonHead => Material { base_sound: SoundType::Stone, sound: SoundRule::Constant(SoundType::Stone), instrument: Instrument::Dragon, offset: Profile::Air },
    PiglinHead => Material { base_sound: SoundType::Stone, sound: SoundRule::Constant(SoundType::Stone), instrument: Instrument::Piglin, offset: Profile::Air },
    Anvil => Material { base_sound: SoundType::Anvil, sound: SoundRule::Constant(SoundType::Anvil), instrument: Instrument::Harp, offset: Profile::Air },
    NetherQuartzOre => Material { base_sound: SoundType::NetherOre, sound: SoundRule::Constant(SoundType::NetherOre), instrument: Instrument::Basedrum, offset: Profile::Air },
    SlimeBlock => Material { base_sound: SoundType::SlimeBlock, sound: SoundRule::Constant(SoundType::SlimeBlock), instrument: Instrument::Harp, offset: Profile::Air },
    HayBlock => Material { base_sound: SoundType::Grass, sound: SoundRule::Constant(SoundType::Grass), instrument: Instrument::Banjo, offset: Profile::Air },
    PackedIce => Material { base_sound: SoundType::Glass, sound: SoundRule::Constant(SoundType::Glass), instrument: Instrument::Chime, offset: Profile::Air },
    PitcherPlant => Material { base_sound: SoundType::Crop, sound: SoundRule::Constant(SoundType::Crop), instrument: Instrument::Harp, offset: Profile::MangrovePropagule },
    NetherWartBlock => Material { base_sound: SoundType::WartBlock, sound: SoundRule::Constant(SoundType::WartBlock), instrument: Instrument::Harp, offset: Profile::Air },
    BoneBlock => Material { base_sound: SoundType::BoneBlock, sound: SoundRule::Constant(SoundType::BoneBlock), instrument: Instrument::Xylophone, offset: Profile::Air },
    DriedGhast => Material { base_sound: SoundType::DriedGhast, sound: SoundRule::Constant(SoundType::DriedGhast), instrument: Instrument::Harp, offset: Profile::Air },
    TubeCoralBlock => Material { base_sound: SoundType::CoralBlock, sound: SoundRule::Constant(SoundType::CoralBlock), instrument: Instrument::Basedrum, offset: Profile::Air },
    BambooSapling => Material { base_sound: SoundType::BambooSapling, sound: SoundRule::Constant(SoundType::BambooSapling), instrument: Instrument::Harp, offset: Profile::MangrovePropagule },
    Bamboo => Material { base_sound: SoundType::Bamboo, sound: SoundRule::Constant(SoundType::Bamboo), instrument: Instrument::Harp, offset: Profile::MangrovePropagule },
    Scaffolding => Material { base_sound: SoundType::Scaffolding, sound: SoundRule::Constant(SoundType::Scaffolding), instrument: Instrument::Harp, offset: Profile::Air },
    Lantern => Material { base_sound: SoundType::Lantern, sound: SoundRule::Constant(SoundType::Lantern), instrument: Instrument::Harp, offset: Profile::Air },
    SweetBerryBush => Material { base_sound: SoundType::SweetBerryBush, sound: SoundRule::Constant(SoundType::SweetBerryBush), instrument: Instrument::Harp, offset: Profile::Air },
    WarpedStem => Material { base_sound: SoundType::Stem, sound: SoundRule::Constant(SoundType::Stem), instrument: Instrument::Bass, offset: Profile::Air },
    WarpedNylium => Material { base_sound: SoundType::Nylium, sound: SoundRule::Constant(SoundType::Nylium), instrument: Instrument::Basedrum, offset: Profile::Air },
    WarpedFungus => Material { base_sound: SoundType::Fungus, sound: SoundRule::Constant(SoundType::Fungus), instrument: Instrument::Harp, offset: Profile::Air },
    NetherSprouts => Material { base_sound: SoundType::NetherSprouts, sound: SoundRule::Constant(SoundType::NetherSprouts), instrument: Instrument::Harp, offset: Profile::MangrovePropagule },
    Shroomlight => Material { base_sound: SoundType::Shroomlight, sound: SoundRule::Constant(SoundType::Shroomlight), instrument: Instrument::Harp, offset: Profile::Air },
    WeepingVines => Material { base_sound: SoundType::WeepingVines, sound: SoundRule::Constant(SoundType::WeepingVines), instrument: Instrument::Harp, offset: Profile::Air },
    CrimsonPlanks => Material { base_sound: SoundType::NetherWood, sound: SoundRule::Constant(SoundType::NetherWood), instrument: Instrument::Bass, offset: Profile::Air },
    CrimsonButton => Material { base_sound: SoundType::NetherWood, sound: SoundRule::Constant(SoundType::NetherWood), instrument: Instrument::Harp, offset: Profile::Air },
    HoneyBlock => Material { base_sound: SoundType::HoneyBlock, sound: SoundRule::Constant(SoundType::HoneyBlock), instrument: Instrument::Harp, offset: Profile::Air },
    HoneycombBlock => Material { base_sound: SoundType::CoralBlock, sound: SoundRule::Constant(SoundType::CoralBlock), instrument: Instrument::Harp, offset: Profile::Air },
    NetheriteBlock => Material { base_sound: SoundType::NetheriteBlock, sound: SoundRule::Constant(SoundType::NetheriteBlock), instrument: Instrument::Harp, offset: Profile::Air },
    AncientDebris => Material { base_sound: SoundType::AncientDebris, sound: SoundRule::Constant(SoundType::AncientDebris), instrument: Instrument::Harp, offset: Profile::Air },
    Lodestone => Material { base_sound: SoundType::Lodestone, sound: SoundRule::Constant(SoundType::Lodestone), instrument: Instrument::Harp, offset: Profile::Air },
    GildedBlackstone => Material { base_sound: SoundType::GildedBlackstone, sound: SoundRule::Constant(SoundType::GildedBlackstone), instrument: Instrument::Basedrum, offset: Profile::Air },
    AmethystBlock => Material { base_sound: SoundType::Amethyst, sound: SoundRule::Constant(SoundType::Amethyst), instrument: Instrument::Harp, offset: Profile::Air },
    AmethystCluster => Material { base_sound: SoundType::AmethystCluster, sound: SoundRule::Constant(SoundType::AmethystCluster), instrument: Instrument::Harp, offset: Profile::Air },
    LargeAmethystBud => Material { base_sound: SoundType::MediumAmethystBud, sound: SoundRule::Constant(SoundType::MediumAmethystBud), instrument: Instrument::Harp, offset: Profile::Air },
    MediumAmethystBud => Material { base_sound: SoundType::LargeAmethystBud, sound: SoundRule::Constant(SoundType::LargeAmethystBud), instrument: Instrument::Harp, offset: Profile::Air },
    SmallAmethystBud => Material { base_sound: SoundType::SmallAmethystBud, sound: SoundRule::Constant(SoundType::SmallAmethystBud), instrument: Instrument::Harp, offset: Profile::Air },
    Tuff => Material { base_sound: SoundType::Tuff, sound: SoundRule::Constant(SoundType::Tuff), instrument: Instrument::Basedrum, offset: Profile::Air },
    PolishedTuff => Material { base_sound: SoundType::PolishedTuff, sound: SoundRule::Constant(SoundType::PolishedTuff), instrument: Instrument::Basedrum, offset: Profile::Air },
    TuffBricks => Material { base_sound: SoundType::TuffBricks, sound: SoundRule::Constant(SoundType::TuffBricks), instrument: Instrument::Basedrum, offset: Profile::Air },
    Calcite => Material { base_sound: SoundType::Calcite, sound: SoundRule::Constant(SoundType::Calcite), instrument: Instrument::Basedrum, offset: Profile::Air },
    PowderSnow => Material { base_sound: SoundType::PowderSnow, sound: SoundRule::Constant(SoundType::PowderSnow), instrument: Instrument::Harp, offset: Profile::Air },
    SculkSensor => Material { base_sound: SoundType::SculkSensor, sound: SoundRule::Constant(SoundType::SculkSensor), instrument: Instrument::Harp, offset: Profile::Air },
    Sculk => Material { base_sound: SoundType::Sculk, sound: SoundRule::Constant(SoundType::Sculk), instrument: Instrument::Harp, offset: Profile::Air },
    SculkVein => Material { base_sound: SoundType::SculkVein, sound: SoundRule::Constant(SoundType::SculkVein), instrument: Instrument::Harp, offset: Profile::Air },
    SculkCatalyst => Material { base_sound: SoundType::SculkCatalyst, sound: SoundRule::Constant(SoundType::SculkCatalyst), instrument: Instrument::Harp, offset: Profile::Air },
    SculkShrieker => Material { base_sound: SoundType::SculkShrieker, sound: SoundRule::Constant(SoundType::SculkShrieker), instrument: Instrument::Harp, offset: Profile::Air },
    CopperGrate => Material { base_sound: SoundType::CopperGrate, sound: SoundRule::Constant(SoundType::CopperGrate), instrument: Instrument::Harp, offset: Profile::Air },
    CopperBulb => Material { base_sound: SoundType::CopperBulb, sound: SoundRule::Constant(SoundType::CopperBulb), instrument: Instrument::Harp, offset: Profile::Air },
    CopperGolemStatue => Material { base_sound: SoundType::CopperGolemStatue, sound: SoundRule::Constant(SoundType::CopperGolemStatue), instrument: Instrument::Harp, offset: Profile::Air },
    PointedDripstone => Material { base_sound: SoundType::PointedDripstone, sound: SoundRule::Constant(SoundType::PointedDripstone), instrument: Instrument::Basedrum, offset: Profile::PointedDripstone },
    CaveVines => Material { base_sound: SoundType::CaveVines, sound: SoundRule::Constant(SoundType::CaveVines), instrument: Instrument::Harp, offset: Profile::Air },
    SporeBlossom => Material { base_sound: SoundType::SporeBlossom, sound: SoundRule::Constant(SoundType::SporeBlossom), instrument: Instrument::Harp, offset: Profile::Air },
    Azalea => Material { base_sound: SoundType::Azalea, sound: SoundRule::Constant(SoundType::Azalea), instrument: Instrument::Harp, offset: Profile::Air },
    FloweringAzalea => Material { base_sound: SoundType::FloweringAzalea, sound: SoundRule::Constant(SoundType::FloweringAzalea), instrument: Instrument::Harp, offset: Profile::Air },
    MossCarpet => Material { base_sound: SoundType::MossCarpet, sound: SoundRule::Constant(SoundType::MossCarpet), instrument: Instrument::Harp, offset: Profile::Air },
    PinkPetals => Material { base_sound: SoundType::PinkPetals, sound: SoundRule::Constant(SoundType::PinkPetals), instrument: Instrument::Harp, offset: Profile::Air },
    LeafLitter => Material { base_sound: SoundType::LeafLitter, sound: SoundRule::Constant(SoundType::LeafLitter), instrument: Instrument::Harp, offset: Profile::Air },
    MossBlock => Material { base_sound: SoundType::Moss, sound: SoundRule::Constant(SoundType::Moss), instrument: Instrument::Harp, offset: Profile::Air },
    BigDripleaf => Material { base_sound: SoundType::BigDripleaf, sound: SoundRule::Constant(SoundType::BigDripleaf), instrument: Instrument::Harp, offset: Profile::Air },
    SmallDripleaf => Material { base_sound: SoundType::SmallDripleaf, sound: SoundRule::Constant(SoundType::SmallDripleaf), instrument: Instrument::Harp, offset: Profile::SmallDripleaf },
    HangingRoots => Material { base_sound: SoundType::HangingRoots, sound: SoundRule::Constant(SoundType::HangingRoots), instrument: Instrument::Harp, offset: Profile::MangrovePropagule },
    RootedDirt => Material { base_sound: SoundType::RootedDirt, sound: SoundRule::Constant(SoundType::RootedDirt), instrument: Instrument::Harp, offset: Profile::Air },
    Mud => Material { base_sound: SoundType::Mud, sound: SoundRule::Constant(SoundType::Mud), instrument: Instrument::Harp, offset: Profile::Air },
    PolishedDeepslate => Material { base_sound: SoundType::PolishedDeepslate, sound: SoundRule::Constant(SoundType::PolishedDeepslate), instrument: Instrument::Basedrum, offset: Profile::Air },
    DeepslateTiles => Material { base_sound: SoundType::DeepslateTiles, sound: SoundRule::Constant(SoundType::DeepslateTiles), instrument: Instrument::Basedrum, offset: Profile::Air },
    DeepslateBricks => Material { base_sound: SoundType::DeepslateBricks, sound: SoundRule::Constant(SoundType::DeepslateBricks), instrument: Instrument::Basedrum, offset: Profile::Air },
    InfestedDeepslate => Material { base_sound: SoundType::Deepslate, sound: SoundRule::Constant(SoundType::Deepslate), instrument: Instrument::Harp, offset: Profile::Air },
    OchreFroglight => Material { base_sound: SoundType::Froglight, sound: SoundRule::Constant(SoundType::Froglight), instrument: Instrument::Harp, offset: Profile::Air },
    DecoratedPot => Material { base_sound: SoundType::Stone, sound: SoundRule::DecoratedPot, instrument: Instrument::Harp, offset: Profile::Air },
    TrialSpawner => Material { base_sound: SoundType::TrialSpawner, sound: SoundRule::Constant(SoundType::TrialSpawner), instrument: Instrument::Basedrum, offset: Profile::Air },
    Vault => Material { base_sound: SoundType::Vault, sound: SoundRule::Constant(SoundType::Vault), instrument: Instrument::Basedrum, offset: Profile::Air },
    HeavyCore => Material { base_sound: SoundType::HeavyCore, sound: SoundRule::Constant(SoundType::HeavyCore), instrument: Instrument::Snare, offset: Profile::Air },
    GunSmithTable => Material { base_sound: SoundType::Wood, sound: SoundRule::Constant(SoundType::Wood), instrument: Instrument::Basedrum, offset: Profile::Air },
    PrimalMagma => Material { base_sound: SoundType::AcFloodBasalt, sound: SoundRule::Constant(SoundType::AcFloodBasalt), instrument: Instrument::Basedrum, offset: Profile::Air },
    FloodBasalt => Material { base_sound: SoundType::AcFloodBasalt, sound: SoundRule::Constant(SoundType::AcFloodBasalt), instrument: Instrument::Harp, offset: Profile::Air },
    PewenBranch => Material { base_sound: SoundType::AcPewenBranch, sound: SoundRule::PewenBranch, instrument: Instrument::Harp, offset: Profile::PewenBranch },
    PewenPines => Material { base_sound: SoundType::Roots, sound: SoundRule::Constant(SoundType::Roots), instrument: Instrument::Harp, offset: Profile::PewenPines },
}
