Args = --no-fallback \
       --allow-incomplete-classpath \
       --report-unsupported-elements-at-runtime \
       --enable-all-security-services \
       --enable-https \
       --enable-url-protocols=http,https,jar \
       -H:+ReportExceptionStackTraces \
       -H:+AddAllCharsets
