package net.caffeinemc.mods.sodium.mixin.features.textures;

/**
 * Compile-time stub for Sodium mixin accessor.
 * At runtime, this is generated by Sodium's mixin system.
 * 
 * @see modules/sodium-1.21.9/common/src/main/java/net/caffeinemc/mods/sodium/mixin/features/textures/NativeImageAccessor.java
 */
public interface NativeImageAccessor {
    long getPixels();
}
