[package]
name = "mattmc_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
alto = { version = "3.0.4", default-features = false }
ash = { version = "0.38", default-features = false, features = ["loaded", "std"] }
glow = "0.18"
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"] }
lewton = "0.10.2"
libc = "0.2"
libloading = "0.8"
lz4_flex = "0.11"
png = "0.17"
serde_json = "1"
shaderc = { version = "0.10.1", features = ["build-from-source"] }
tracy-client = { version = "0.18.4", default-features = false, features = ["enable", "manual-lifetime", "only-localhost"], optional = true }
xxhash-rust = { version = "0.8", features = ["xxh32"] }

[dev-dependencies]
raw-window-handle = "0.6.2"
winit = "0.30.13"

[features]
tracy = ["dep:tracy-client"]

[build-dependencies]
cmake = "0.1"

[profile.dev]
opt-level = 0
debug = true
strip = "none"
debug-assertions = true
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256
rpath = false

[profile.release]
opt-level = 3
debug = false
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = "thin"
panic = "abort"
incremental = false
codegen-units = 1
rpath = false
