package net.caffeinemc.mods.sodium.mixin.core;

import com.mojang.blaze3d.opengl.GlProgram;
import com.mojang.blaze3d.pipeline.RenderPipeline;

/**
 * Compile-time stub for Sodium mixin accessor.
 * At runtime, this is generated by Sodium's mixin system.
 */
public interface GlCommandEncoderAccessor {
    void sodium$applyPipelineState(RenderPipeline pipeline);
    void sodium$setLastProgram(GlProgram program);
}
