package net.caffeinemc.mods.sodium.mixin.features.gui.hooks.debug;

import net.minecraft.client.gui.components.debug.DebugScreenEntry;
import net.minecraft.resources.ResourceLocation;
import java.util.Map;

/**
 * Compile-time stub for Sodium mixin accessor.
 * At runtime, this is generated by Sodium's mixin system.
 */
public interface DebugScreenEntriesAccessor {
    static Map<ResourceLocation, DebugScreenEntry> getEntries() {
        return null;
    }
}
