package net.vulkanic;

import java.nio.ByteBuffer;
import java.nio.FloatBuffer;

/**
 * Interface for graphics backend implementations.
 * This interface defines the contract that all backends (OpenGL, Vulkan) must implement.
 */
public interface GraphicsBackend {
    
    // Context operations
    /**
     * Gets the current graphics context (platform-specific).
     * On Windows, this returns the WGL context handle.
     * Returns 0 or NULL if no context is current.
     */
    @Deprecated
    long getGraphicsContext();
    
    @Deprecated
    void bindTexture(int textureId);
    @Deprecated
    void bindTexture(int target, int textureId);  // For explicit target binding
    
    /**
     * Generates mipmaps for a texture.
     * This is a Vulkan-compatible replacement for the deprecated generateMipmap(int target) method.
     * 
     * In OpenGL: Maps to glGenerateMipmap() on the specified texture
     * In Vulkan: Maps to vkCmdBlitImage() commands in a command buffer to generate each mip level
     * 
     * This method explicitly specifies which texture to generate mipmaps for, eliminating the
     * dependency on OpenGL's texture binding state. The texture should have been created with
     * mipmap levels allocated.
     * 
     * Important architectural notes for Vulkan compatibility:
     * - In Vulkan, mipmap generation requires a series of image blit operations
     * - Each mip level is generated by blitting/downsampling from the previous level
     * - The texture must be in the correct layout (TRANSFER_SRC/DST) during generation
     * - Operations must be recorded in a command buffer and submitted
     * 
     * For OpenGL backend:
     * - Texture is temporarily bound to GL_TEXTURE_2D
     * - glGenerateMipmap is called
     * - Previous binding state is preserved
     * 
     * Future evolution: This will take a CommandBuffer parameter for Vulkan:
     *   void generateTextureMipmaps(CommandBuffer cmdBuffer, int textureId)
     * 
     * @param textureId The OpenGL texture ID (or future Vulkan texture handle) to generate mipmaps for
     */
    void generateTextureMipmaps(int textureId);
    
    /**
     * Sets the dynamic viewport state for rendering.
     * This is a Vulkan-compatible replacement for the deprecated viewport() method.
     * 
     * In OpenGL: Maps to glViewport()
     * In Vulkan: Maps to vkCmdSetViewport() (dynamic state)
     * 
     * The viewport defines the transformation from normalized device coordinates to window coordinates.
     * This is dynamic state that can be changed per-frame or even between draw calls.
     * 
     * Future evolution: This method will take a CommandBuffer parameter to support
     * Vulkan's command buffer recording model:
     *   void setDynamicViewport(CommandBuffer cmdBuffer, int x, int y, int width, int height)
     * 
     * @param x The x coordinate of the viewport's lower-left corner
     * @param y The y coordinate of the viewport's lower-left corner
     * @param width The width of the viewport in pixels
     * @param height The height of the viewport in pixels
     */
    void setDynamicViewport(int x, int y, int width, int height);
    
    /**
     * Clears framebuffer attachments (color and/or depth buffers).
     * This is a Vulkan-compatible replacement for the deprecated clear(int mask) method.
     * 
     * In OpenGL: Maps to glClear(mask) where mask is constructed from the boolean parameters
     * In Vulkan: Maps to VkRenderPassBeginInfo.pClearValues and LoadOp::CLEAR
     * 
     * This method explicitly specifies which attachments to clear, making it clear to both
     * the developer and the future Vulkan backend what needs to be cleared.
     * 
     * Important architectural notes for Vulkan compatibility:
     * - In Vulkan, clearing happens at render pass begin time, not as a separate command
     * - The clear values are specified in VkRenderPassBeginInfo when calling vkCmdBeginRenderPass
     * - For now, this API allows clearing at any time (OpenGL-style), but callers should
     *   ideally call this at the start of rendering to a framebuffer to match Vulkan semantics
     * 
     * Future evolution: This will be replaced by render pass API where clear values are
     * specified when beginning a render pass:
     *   RenderPassBeginInfo.setClearColorValue(r, g, b, a)
     *   RenderPassBeginInfo.setClearDepthValue(depth)
     *   cmdBeginRenderPass(commandBuffer, renderPassBeginInfo)
     * 
     * @param clearColor If true, clears the color buffer
     * @param clearDepth If true, clears the depth buffer
     */
    void clearAttachments(boolean clearColor, boolean clearDepth);
    
    /**
     * Binds a shader program for rendering.
     * This is a Vulkan-compatible replacement for the deprecated useProgram(int programId) method.
     * 
     * In OpenGL: Maps to glUseProgram()
     * In Vulkan: Will map to vkCmdBindPipeline() with a graphics pipeline containing the shader modules
     * 
     * This method explicitly binds a shader program, making it clear which program will be used
     * for subsequent draw commands. The program should have been previously compiled and linked.
     * 
     * Important architectural notes for Vulkan compatibility:
     * - In Vulkan, shaders are part of a pipeline state object (PSO)
     * - The pipeline includes shaders, vertex input state, rasterization state, etc.
     * - This method is an intermediate step - future versions will use full PSO
     * - For now, it provides a simple 1:1 mapping while maintaining Vulkan compatibility
     * 
     * For OpenGL backend:
     * - Directly calls glUseProgram with the program ID
     * - Program 0 unbinds the current program
     * 
     * Future evolution: This will be part of pipeline state objects:
     *   PipelineStateObject pso = createPipeline(shaderProgram, ...);
     *   cmdBindPipeline(commandBuffer, pso);
     * 
     * @param programId The shader program ID to bind (0 to unbind)
     */
    void bindShaderProgram(int programId);
    
    @Deprecated
    void enableBlend();
    @Deprecated
    void disableBlend();
    @Deprecated
    void enable(int cap);
    @Deprecated
    void disable(int cap);
    
    /**
     * Sets the dynamic depth comparison function for rendering.
     * This is a Vulkan-compatible replacement for the deprecated setDepthTestFunction() method.
     * 
     * In OpenGL: Maps to glDepthFunc()
     * In Vulkan: Maps to vkCmdSetDepthCompareOp() (dynamic state in command buffer)
     * 
     * The depth comparison function determines how incoming fragment depths are compared
     * against the depth buffer. Common values include GL_LESS, GL_LEQUAL, GL_EQUAL, etc.
     * This is dynamic state that can be changed per-frame or even between draw calls.
     * 
     * Important architectural notes for Vulkan compatibility:
     * - In Vulkan, this will be a dynamic state command recorded in command buffers
     * - This allows changing the depth compare operation without creating new pipeline state objects
     * - Must be called within an active render pass in Vulkan
     * - For now, this provides a simple 1:1 mapping while maintaining Vulkan compatibility
     * 
     * For OpenGL backend:
     * - Directly calls glDepthFunc with the specified comparison function
     * - Changes take effect immediately for subsequent draw calls
     * - Part of the global OpenGL state machine
     * 
     * Future evolution: This may take a CommandBuffer parameter for Vulkan:
     *   void setDynamicDepthFunc(CommandBuffer cmdBuffer, int compareOp)
     * 
     * @param compareOp The depth comparison function (e.g., GL_LESS, GL_LEQUAL, GL_EQUAL, GL_GREATER, GL_GEQUAL, GL_ALWAYS, GL_NEVER)
     */
    void setDynamicDepthFunc(int compareOp);
    
    /**
     * Sets the dynamic depth write mask for rendering.
     * This is a Vulkan-compatible replacement for the deprecated setDepthWriteEnabled() method.
     * 
     * In OpenGL: Maps to glDepthMask()
     * In Vulkan: Maps to vkCmdSetDepthWriteEnable() (dynamic state in command buffer)
     * 
     * The depth write mask controls whether depth values are written to the depth buffer.
     * This is dynamic state that can be changed per-frame or even between draw calls.
     * 
     * Important architectural notes for Vulkan compatibility:
     * - In Vulkan, this will be a dynamic state command recorded in command buffers
     * - This allows changing the depth write enable without creating new pipeline state objects
     * - Must be called within an active render pass in Vulkan
     * - For now, this provides a simple 1:1 mapping while maintaining Vulkan compatibility
     * 
     * For OpenGL backend:
     * - Directly calls glDepthMask with the specified parameter
     * - Changes take effect immediately for subsequent draw calls
     * - Part of the global OpenGL state machine
     * 
     * Future evolution: This may take a CommandBuffer parameter for Vulkan:
     *   void setDynamicDepthWriteMask(CommandBuffer cmdBuffer, boolean enabled)
     * 
     * @param enabled Whether to enable depth writes (true to enable, false to disable)
     */
    void setDynamicDepthWriteMask(boolean enabled);
    
    /**
     * Sets the dynamic color write mask for rendering.
     * This is a Vulkan-compatible replacement for the deprecated setColorWriteMask() method.
     * 
     * In OpenGL: Maps to glColorMask()
     * In Vulkan: Maps to vkCmdSetColorWriteMaskEXT() (dynamic state in command buffer)
     * 
     * The color write mask controls which color components are written to the framebuffer.
     * This is dynamic state that can be changed per-frame or even between draw calls.
     * 
     * Important architectural notes for Vulkan compatibility:
     * - In Vulkan, this will be a dynamic state command recorded in command buffers
     * - This allows changing the write mask without creating new pipeline state objects
     * - Must be called within an active render pass in Vulkan
     * - For now, this provides a simple 1:1 mapping while maintaining Vulkan compatibility
     * 
     * For OpenGL backend:
     * - Directly calls glColorMask with the specified parameters
     * - Changes take effect immediately for subsequent draw calls
     * - Part of the global OpenGL state machine
     * 
     * Future evolution: This may take a CommandBuffer parameter for Vulkan:
     *   void setDynamicColorWriteMask(CommandBuffer cmdBuffer, boolean r, boolean g, boolean b, boolean a)
     * 
     * @param r Whether to write red component (true to enable, false to disable)
     * @param g Whether to write green component (true to enable, false to disable)
     * @param b Whether to write blue component (true to enable, false to disable)
     * @param a Whether to write alpha component (true to enable, false to disable)
     */
    void setDynamicColorWriteMask(boolean r, boolean g, boolean b, boolean a);
    
    /**
     * Sets the dynamic face culling mode for rendering.
     * This is a Vulkan-compatible replacement for the deprecated glCullFace() method
     * and enable/disable(GL_CULL_FACE) methods.
     * 
     * In OpenGL: Maps to glEnable/glDisable(GL_CULL_FACE) + glCullFace(mode)
     * In Vulkan: Maps to VkPipelineRasterizationStateCreateInfo.cullMode or vkCmdSetCullModeEXT() (dynamic state)
     * 
     * Face culling discards primitives based on their facing direction relative to the viewer.
     * This is dynamic state that can be changed per-frame or even between draw calls.
     * 
     * Important architectural notes for Vulkan compatibility:
     * - In Vulkan, this will be a dynamic state command recorded in command buffers
     * - This allows changing the cull mode without creating new pipeline state objects
     * - Must be called within an active render pass in Vulkan
     * - For now, this provides a simple 1:1 mapping while maintaining Vulkan compatibility
     * 
     * For OpenGL backend:
     * - Calls glEnable/glDisable(GL_CULL_FACE) based on enableCulling parameter
     * - If culling is enabled, calls glCullFace(cullFaceMode)
     * - Changes take effect immediately for subsequent draw calls
     * - Part of the global OpenGL state machine
     * 
     * Future evolution: This may take a CommandBuffer parameter for Vulkan:
     *   void setDynamicCullMode(CommandBuffer cmdBuffer, boolean enableCulling, int cullFaceMode)
     * 
     * @param enableCulling Whether to enable face culling (true to enable, false to disable)
     * @param cullFaceMode The faces to cull when enabled (GL_FRONT, GL_BACK, or GL_FRONT_AND_BACK)
     *                     This parameter is ignored if enableCulling is false
     */
    void setDynamicCullMode(boolean enableCulling, int cullFaceMode);
    
    /**
     * Sets the dynamic blend state for rendering.
     * This is a Vulkan-compatible replacement for the deprecated enableBlend(), disableBlend(),
     * enable(GL_BLEND), and disable(GL_BLEND) methods.
     * 
     * In OpenGL: Maps to glEnable/glDisable(GL_BLEND) + glBlendFunc(src, dst)
     * In Vulkan: Maps to VkPipelineColorBlendStateCreateInfo or vkCmdSetColorBlendEnableEXT() (dynamic state)
     * 
     * Blending controls how the output color from the fragment shader is combined with the color
     * already in the framebuffer. This is dynamic state that can be changed per-frame or even between draw calls.
     * 
     * Important architectural notes for Vulkan compatibility:
     * - In Vulkan, this will be a dynamic state command recorded in command buffers
     * - This allows changing the blend enable/disable and blend function without creating new pipeline state objects
     * - Must be called within an active render pass in Vulkan
     * - For now, this provides a simple 1:1 mapping while maintaining Vulkan compatibility
     * 
     * For OpenGL backend:
     * - Calls glEnable/glDisable(GL_BLEND) based on enabled parameter
     * - If blending is enabled, calls glBlendFunc(srcFactor, dstFactor)
     * - Changes take effect immediately for subsequent draw calls
     * - Part of the global OpenGL state machine
     * 
     * Future evolution: This may take a CommandBuffer parameter for Vulkan:
     *   void setDynamicBlendState(CommandBuffer cmdBuffer, boolean enabled, int srcFactor, int dstFactor)
     * 
     * Future evolution: May expand to support separate RGB/Alpha blend functions:
     *   void setDynamicBlendState(CommandBuffer cmdBuffer, boolean enabled, 
     *                             int srcColorFactor, int dstColorFactor,
     *                             int srcAlphaFactor, int dstAlphaFactor)
     * 
     * @param enabled Whether to enable blending (true to enable, false to disable)
     * @param srcFactor The source blend factor (e.g., GL_SRC_ALPHA, GL_ONE)
     *                  This parameter is ignored if enabled is false
     * @param dstFactor The destination blend factor (e.g., GL_ONE_MINUS_SRC_ALPHA, GL_ZERO)
     *                  This parameter is ignored if enabled is false
     */
    void setDynamicBlendState(boolean enabled, int srcFactor, int dstFactor);
    
    // Scissor operations
    
    /**
     * Sets the dynamic scissor rectangle for rendering.
     * This is a Vulkan-compatible replacement for the deprecated setScissorBox() method.
     * 
     * In OpenGL: Maps to glScissor()
     * In Vulkan: Maps to vkCmdSetScissor() (dynamic state)
     * 
     * The scissor test discards fragments outside the scissor rectangle.
     * This is dynamic state that can be changed per-frame or even between draw calls.
     * 
     * Future evolution: This method will take a CommandBuffer parameter to support
     * Vulkan's command buffer recording model:
     *   void setDynamicScissor(CommandBuffer cmdBuffer, int x, int y, int width, int height)
     * 
     * @param x The x coordinate of the scissor rectangle's lower-left corner
     * @param y The y coordinate of the scissor rectangle's lower-left corner
     * @param width The width of the scissor rectangle in pixels
     * @param height The height of the scissor rectangle in pixels
     */
    void setDynamicScissor(int x, int y, int width, int height);
    
    /**
     * Sets the texture upload alignment for subsequent texture upload operations.
     * This is a Vulkan-compatible replacement for setPixelStoreMode(GL_UNPACK_ALIGNMENT, value).
     * 
     * In OpenGL: Maps to glPixelStorei(GL_UNPACK_ALIGNMENT, alignment)
     * In Vulkan: Will be used as parameter in vkCmdCopyBufferToImage and image upload operations
     * 
     * Alignment specifies the byte alignment of pixel rows in memory. Common values:
     * - 1: Tightly packed (no padding)
     * - 4: Default OpenGL alignment (word-aligned)
     * - 8: 64-bit aligned
     * 
     * This affects how texture data is read from client memory during texture uploads.
     * In Vulkan, this will be part of the VkBufferImageCopy structure rather than global state.
     * 
     * @param alignment The byte alignment (must be 1, 2, 4, or 8)
     */
    void setTextureUploadAlignment(int alignment);
    
    /**
     * Sets the row length for texture uploads (in pixels).
     * This is a Vulkan-compatible replacement for setPixelStoreMode(GL_UNPACK_ROW_LENGTH, rowLength).
     * 
     * In OpenGL: Maps to glPixelStorei(GL_UNPACK_ROW_LENGTH, rowLength)
     * In Vulkan: Will be used to calculate bufferRowLength in VkBufferImageCopy
     * 
     * Row length defines the number of pixels in a row of the source data.
     * If 0, the row length is assumed to be the same as the image width.
     * 
     * @param rowLength The row length in pixels (0 for automatic)
     */
    void setTextureUploadRowLength(int rowLength);
    
    /**
     * Sets the number of rows to skip before reading pixel data.
     * This is a Vulkan-compatible replacement for setPixelStoreMode(GL_UNPACK_SKIP_ROWS, skipRows).
     * 
     * In OpenGL: Maps to glPixelStorei(GL_UNPACK_SKIP_ROWS, skipRows)
     * In Vulkan: Will be used to calculate buffer offset in VkBufferImageCopy
     * 
     * @param skipRows The number of rows to skip (0 for none)
     */
    void setTextureUploadSkipRows(int skipRows);
    
    /**
     * Sets the number of pixels to skip before reading pixel data.
     * This is a Vulkan-compatible replacement for setPixelStoreMode(GL_UNPACK_SKIP_PIXELS, skipPixels).
     * 
     * In OpenGL: Maps to glPixelStorei(GL_UNPACK_SKIP_PIXELS, skipPixels)
     * In Vulkan: Will be used to calculate buffer offset in VkBufferImageCopy
     * 
     * @param skipPixels The number of pixels to skip (0 for none)
     */
    void setTextureUploadSkipPixels(int skipPixels);
    
    /**
     * Sets the texture download alignment for subsequent pixel read operations.
     * This is a Vulkan-compatible replacement for setPixelStoreMode(GL_PACK_ALIGNMENT, value).
     * 
     * In OpenGL: Maps to glPixelStorei(GL_PACK_ALIGNMENT, alignment)
     * In Vulkan: Will be used as parameter in vkCmdCopyImageToBuffer
     * 
     * Alignment specifies the byte alignment of pixel rows when reading from the GPU.
     * Common values: 1 (tightly packed), 4 (default word-aligned), 8 (64-bit aligned)
     * 
     * @param alignment The byte alignment (must be 1, 2, 4, or 8)
     */
    void setTextureDownloadAlignment(int alignment);
    
    // Framebuffer operations
    @Deprecated
    void attachFramebuffer(int target, int fbo);
    @Deprecated
    void attachTextureToFramebuffer(int target, int attachment, int textarget, int texture, int level);
    
    // Buffer operations  
    @Deprecated
    void attachBuffer(int target, int buffer);
    
    // Direct State Access buffer operations
    @Deprecated
    int createBufferDSA();
    @Deprecated
    void namedBufferDataDSA(int buffer, long size, int usage);
    @Deprecated
    void namedBufferDataDSA(int buffer, java.nio.ByteBuffer data, int usage);
    @Deprecated
    void namedBufferSubDataDSA(int buffer, long offset, java.nio.ByteBuffer data);
    @Deprecated
    void namedBufferStorageDSA(int buffer, long size, int flags);
    @Deprecated
    void namedBufferStorageDSA(int buffer, java.nio.ByteBuffer data, int flags);
    @Deprecated
    java.nio.ByteBuffer mapNamedBufferRangeDSA(int buffer, long offset, long length, int access);
    @Deprecated
    void unmapNamedBufferDSA(int buffer);
    @Deprecated
    void flushMappedNamedBufferRangeDSA(int buffer, long offset, long length);
    @Deprecated
    void copyNamedBufferSubDataDSA(int readBuffer, int writeBuffer, long readOffset, long writeOffset, long size);
    
    // Direct State Access framebuffer operations
    @Deprecated
    int createFramebufferDSA();
    @Deprecated
    void namedFramebufferTextureDSA(int framebuffer, int attachment, int texture, int level);
    void blitNamedFramebufferDSA(int readFramebuffer, int drawFramebuffer, int srcX0, int srcY0, int srcX1, int srcY1, 
                                  int dstX0, int dstY0, int dstX1, int dstY1, int mask, int filter);
    
    // Texture unit and parameter operations
    @Deprecated
    void activateTextureUnit(int unit);
    @Deprecated
    void configureTextureParameter(int target, int pname, int param);
    @Deprecated
    int createTexture();
    
    /**
     * Deletes a texture and frees its associated GPU resources.
     * This is a Vulkan-compatible replacement for the deprecated removeTexture() method.
     * 
     * In OpenGL: Maps to glDeleteTextures(textureId)
     * In Vulkan: Will map to vkDestroyImageView + vkDestroyImage + vkFreeMemory
     * 
     * This method destroys a texture object and frees all GPU resources associated with it,
     * including image memory, image views, and samplers. After calling this method, the
     * texture ID becomes invalid and must not be used again.
     * 
     * Important architectural notes for Vulkan compatibility:
     * - In Vulkan, texture deletion requires destroying multiple objects in the correct order
     * - ImageView must be destroyed before the Image
     * - Image must be destroyed before freeing memory
     * - Sampler (if separate) must also be destroyed
     * - For now, this provides a simple 1:1 mapping to glDeleteTextures
     * 
     * For OpenGL backend:
     * - Directly calls glDeleteTextures with the texture ID
     * - OpenGL automatically handles cleanup of texture state
     * - Texture ID is immediately available for reuse
     * 
     * Future evolution: This may take additional parameters for Vulkan:
     *   void deleteTexture(int textureId, boolean destroyImageView, boolean destroySampler)
     * 
     * Best practices:
     * - Always delete textures when they are no longer needed to free GPU memory
     * - Do not delete a texture that is currently bound or in use by pending draw calls
     * - Texture IDs should not be reused after deletion
     * 
     * @param textureId The texture ID to delete (must be a valid texture created by createTexture)
     */
    void deleteTexture(int textureId);
    
    /**
     * Creates a 2D texture with explicit parameters.
     * This is a Vulkan-compatible replacement for the deprecated createTexture() method.
     * 
     * In OpenGL: Creates texture with glGenTextures, allocates storage with glTexImage2D, sets filters
     * In Vulkan: Will create VkImage + VkImageView with explicit format, dimensions, and sampler
     * 
     * This method creates a complete 2D texture object with all necessary parameters specified upfront.
     * Unlike the deprecated createTexture() which only generates a texture ID, this method fully
     * initializes the texture with size, format, and filtering parameters.
     * 
     * Important architectural notes for Vulkan compatibility:
     * - In Vulkan, textures (images) must be created with explicit format and dimensions
     * - Memory must be allocated and bound to the image
     * - Image views provide access to the image data
     * - Samplers define filtering and addressing modes
     * - All these parameters are immutable after creation (mostly)
     * 
     * For OpenGL backend:
     * - Generates a new texture ID with glGenTextures
     * - Binds the texture temporarily
     * - Allocates storage with glTexImage2D using the specified parameters
     * - Sets minification and magnification filters
     * - Unbinds and restores previous texture binding
     * 
     * Future evolution: This may return a TextureHandle object instead of int:
     *   TextureHandle createTexture2D(int width, int height, TextureFormat format, TextureUsage usage)
     * 
     * Supported internal formats (subset of common formats):
     * - GL_RGBA / GL_RGBA8 / GL_RGBA16 - 4-component color
     * - GL_RGB / GL_RGB8 - 3-component color
     * - GL_DEPTH_COMPONENT / GL_DEPTH_COMPONENT24 - Depth textures
     * - GL_DEPTH24_STENCIL8 - Combined depth-stencil
     * 
     * Supported filter modes:
     * - GL_NEAREST - Nearest-neighbor sampling (blocky)
     * - GL_LINEAR - Bilinear filtering (smooth)
     * - GL_LINEAR_MIPMAP_LINEAR - Trilinear filtering (requires mipmaps)
     * 
     * Best practices:
     * - Specify the minimum required precision to save GPU memory
     * - Use GL_LINEAR for smooth rendering, GL_NEAREST for pixel art
     * - Generate mipmaps after creation using generateTextureMipmaps() if needed
     * - Call deleteTexture() when the texture is no longer needed
     * 
     * @param width The width of the texture in pixels (must be > 0)
     * @param height The height of the texture in pixels (must be > 0)
     * @param internalFormat The internal storage format (e.g., GL_RGBA, GL_RGBA16)
     * @param minFilter The minification filter (e.g., GL_LINEAR, GL_NEAREST)
     * @param magFilter The magnification filter (e.g., GL_LINEAR, GL_NEAREST)
     * @return The texture ID that can be used to reference this texture
     */
    int createTexture2D(int width, int height, int internalFormat, int minFilter, int magFilter);
    
    /**
     * Sets the dynamic depth bias (polygon offset) for rendering.
     * This is a Vulkan-compatible replacement for the deprecated configurePolygonOffset() method.
     * 
     * In OpenGL: Maps to glPolygonOffset(slopeFactor, constantFactor)
     * In Vulkan: Maps to vkCmdSetDepthBias(commandBuffer, constantFactor, 0.0f, slopeFactor)
     * 
     * Depth bias adds an offset to depth values to prevent z-fighting and shadow acne.
     * This is dynamic state that can be changed per-frame or even between draw calls.
     * 
     * Important architectural notes for Vulkan compatibility:
     * - In Vulkan, this will be a dynamic state command recorded in command buffers
     * - This allows changing the depth bias without creating new pipeline state objects
     * - Must be called within an active render pass in Vulkan
     * - For now, this provides a simple 1:1 mapping while maintaining Vulkan compatibility
     * 
     * For OpenGL backend:
     * - Directly calls glPolygonOffset with the specified parameters
     * - Changes take effect immediately for subsequent draw calls
     * - Part of the global OpenGL state machine
     * 
     * Future evolution: This may take a CommandBuffer parameter for Vulkan:
     *   void setDynamicDepthBias(CommandBuffer cmdBuffer, float slopeFactor, float constantFactor)
     * 
     * @param slopeFactor Scales the maximum depth slope (factor parameter in OpenGL)
     * @param constantFactor Scales the minimum resolvable depth value (units parameter in OpenGL)
     */
    void setDynamicDepthBias(float slopeFactor, float constantFactor);
    
    /**
     * Sets the dynamic logic operation for framebuffer blending.
     * This is a Vulkan-compatible replacement for the deprecated configureLogicOp() method.
     * 
     * In OpenGL: Maps to glLogicOp(logicOp)
     * In Vulkan: Set as part of VkPipelineColorBlendStateCreateInfo.logicOp
     * 
     * Logic operations perform bitwise operations between source and destination fragments
     * during blending. This is dynamic state that can be changed per-frame or between draw calls.
     * 
     * Important architectural notes for Vulkan compatibility:
     * - In Vulkan, logic operations are typically part of pipeline state
     * - However, VK_EXT_extended_dynamic_state3 allows dynamic logic op
     * - Must be enabled with GL_COLOR_LOGIC_OP (OpenGL) or logicOpEnable (Vulkan)
     * - For now, this provides a simple 1:1 mapping while maintaining Vulkan compatibility
     * 
     * For OpenGL backend:
     * - Directly calls glLogicOp with the specified operation
     * - Changes take effect immediately for subsequent draw calls
     * - Part of the global OpenGL state machine
     * 
     * Future evolution: This may take a CommandBuffer parameter for Vulkan:
     *   void setDynamicLogicOp(CommandBuffer cmdBuffer, int logicOp)
     * 
     * Common logic operations:
     * - GL_COPY / VK_LOGIC_OP_COPY: Source (default)
     * - GL_AND / VK_LOGIC_OP_AND: Source AND Destination
     * - GL_OR / VK_LOGIC_OP_OR: Source OR Destination
     * - GL_XOR / VK_LOGIC_OP_XOR: Source XOR Destination
     * - GL_INVERT / VK_LOGIC_OP_INVERT: NOT Destination
     * 
     * @param logicOp The logic operation to use (e.g., GL_COPY, GL_AND, GL_OR, GL_XOR, GL_INVERT)
     */
    void setDynamicLogicOp(int logicOp);
    
    /**
     * Sets the dynamic polygon rasterization mode.
     * This is a Vulkan-compatible replacement for the deprecated configurePolygonMode() method.
     * 
     * In OpenGL: Maps to glPolygonMode(cullFace, fillMode)
     * In Vulkan: Set as part of VkPipelineRasterizationStateCreateInfo.polygonMode, or use vkCmdSetPolygonModeEXT
     * 
     * Polygon mode controls how polygons are rasterized (filled, wireframe, or points).
     * This is dynamic state that can be changed per-frame or between draw calls.
     * 
     * Important architectural notes for Vulkan compatibility:
     * - In Vulkan, polygon mode is typically part of pipeline state
     * - However, VK_EXT_extended_dynamic_state3 allows dynamic polygon mode
     * - Must be called within an active render pass in Vulkan
     * - For now, this provides a simple 1:1 mapping while maintaining Vulkan compatibility
     * 
     * For OpenGL backend:
     * - Directly calls glPolygonMode with the specified parameters
     * - Changes take effect immediately for subsequent draw calls
     * - Part of the global OpenGL state machine
     * 
     * Future evolution: This may take a CommandBuffer parameter for Vulkan:
     *   void setDynamicPolygonMode(CommandBuffer cmdBuffer, int cullFace, int fillMode)
     * 
     * Common polygon modes:
     * - GL_FILL / VK_POLYGON_MODE_FILL: Fill the interior of polygons
     * - GL_LINE / VK_POLYGON_MODE_LINE: Draw polygon edges as line segments
     * - GL_POINT / VK_POLYGON_MODE_POINT: Draw polygon vertices as points
     * 
     * Common cull faces:
     * - GL_FRONT / VK_CULL_MODE_FRONT_BIT: Apply to front-facing polygons
     * - GL_BACK / VK_CULL_MODE_BACK_BIT: Apply to back-facing polygons
     * - GL_FRONT_AND_BACK: Apply to both front and back-facing polygons
     * 
     * @param cullFace Which face(s) the polygon mode applies to (GL_FRONT, GL_BACK, GL_FRONT_AND_BACK)
     * @param fillMode How to rasterize the polygon (GL_FILL, GL_LINE, GL_POINT)
     */
    void setDynamicPolygonMode(int cullFace, int fillMode);
    
    /**
     * Draws primitives using vertex array data.
     * This is a Vulkan-compatible replacement for the deprecated drawPrimitiveArrays() method.
     * 
     * In OpenGL: Maps to glDrawArrays()
     * In Vulkan: Maps to vkCmdDraw() in a command buffer
     * 
     * This method draws primitives using the currently bound vertex array object (VAO) and
     * shader program. The vertex data is read from the bound vertex buffers starting at the
     * specified vertex index.
     * 
     * Important architectural notes for Vulkan compatibility:
     * - In Vulkan, this will be recorded as a vkCmdDraw command in a command buffer
     * - The vertex buffers, index buffers, and pipeline must be bound before calling
     * - This must be called within an active render pass
     * - For now, this provides a simple 1:1 mapping while maintaining Vulkan compatibility
     * 
     * For OpenGL backend:
     * - Directly calls glDrawArrays with the specified parameters
     * - Uses the currently bound VAO and shader program
     * - Executes immediately
     * 
     * Future evolution: This will take a CommandBuffer parameter for Vulkan:
     *   void cmdDrawArrays(CommandBuffer cmdBuffer, int mode, int firstVertex, int vertexCount)
     * 
     * @param mode The primitive topology (e.g., GL_TRIANGLES, GL_TRIANGLE_FAN)
     * @param firstVertex Index of the first vertex to draw
     * @param vertexCount Number of vertices to draw
     */
    void cmdDrawArrays(int mode, int firstVertex, int vertexCount);
    
    /**
     * Draws indexed primitives using an index buffer.
     * This is a Vulkan-compatible replacement for the deprecated drawIndexedElements() method.
     * 
     * In OpenGL: Maps to glDrawElements()
     * In Vulkan: Maps to vkCmdDrawIndexed() in a command buffer
     * 
     * This method draws primitives using the currently bound vertex array object (VAO) and
     * index buffer. The indices are read from the bound element array buffer starting at the
     * specified offset.
     * 
     * Important architectural notes for Vulkan compatibility:
     * - In Vulkan, this will be recorded as a vkCmdDrawIndexed command in a command buffer
     * - The vertex buffers, index buffer, and pipeline must be bound before calling
     * - This must be called within an active render pass
     * - For now, this provides a simple 1:1 mapping while maintaining Vulkan compatibility
     * 
     * For OpenGL backend:
     * - Directly calls glDrawElements with the specified parameters
     * - Uses the currently bound VAO, element array buffer, and shader program
     * - Executes immediately
     * 
     * Future evolution: This will take a CommandBuffer parameter for Vulkan:
     *   void cmdDrawIndexed(CommandBuffer cmdBuffer, int mode, int indexCount, int indexType, long indicesOffset)
     * 
     * @param mode The primitive topology (e.g., GL_TRIANGLES, GL_TRIANGLE_FAN)
     * @param indexCount Number of indices to draw
     * @param indexType Data type of indices (e.g., GL_UNSIGNED_SHORT, GL_UNSIGNED_INT)
     * @param indicesOffset Byte offset in the index buffer where indices start
     */
    void cmdDrawIndexed(int mode, int indexCount, int indexType, long indicesOffset);
    
    // Drawing operations
    @Deprecated
    void configureBlendFunc(int srcRgb, int dstRgb, int srcAlpha, int dstAlpha);
    
    // Error checking
    @Deprecated
    int checkForErrors();
    
    // Texture pixel data transfer
    @Deprecated
    void transferTexture2DImage(int tgt, int lvl, int intfmt, int w, int h, int bdr, int fmt, int typ, java.nio.ByteBuffer pix);
    @Deprecated
    void transferTexture2DSubregion(int tgt, int lvl, int xoff, int yoff, int w, int h, int fmt, int typ, long pix);
    @Deprecated
    void transferTexture2DSubregionBuf(int tgt, int lvl, int xoff, int yoff, int w, int h, int fmt, int typ, java.nio.ByteBuffer pix);
    
    // GPU buffer lifecycle
    @Deprecated
    int allocateBufferObject();
    @Deprecated
    void releaseBufferObject(int buf);
    @Deprecated
    void fillBufferWithData(int tgt, java.nio.ByteBuffer dat, int usg);
    @Deprecated
    void fillBufferWithSize(int tgt, long sz, int usg);
    @Deprecated
    void fillBufferSubregion(int tgt, long off, java.nio.ByteBuffer dat);
    
    // Vertex array objects
    @Deprecated
    int createVertexArrayObject();
    @Deprecated
    void selectVertexArray(int vao);
    
    // Buffer memory mapping
    @Deprecated
    java.nio.ByteBuffer mapBufferRegion(int tgt, int off, int len, int acc);
    @Deprecated
    void unmapBufferData(int tgt);
    
    // Framebuffer lifecycle
    @Deprecated
    int generateFramebufferObject();
    @Deprecated
    void destroyFramebufferObject(int fbo);
    @Deprecated
    void copyFramebufferRegion(int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1, int msk, int flt);
    
    // Shader pipeline
    @Deprecated
    int constructShaderObject(int shaderType);
    @Deprecated
    void disposeShaderObject(int shader);
    @Deprecated
    void compileShaderSource(int shader);
    @Deprecated
    int constructProgramObject();
    @Deprecated
    void disposeProgramObject(int program);
    @Deprecated
    void linkProgramBinary(int program);
    @Deprecated
    void attachShaderToProgram(int program, int shader);
    @Deprecated
    int queryProgramParameter(int program, int pname);
    @Deprecated
    int queryShaderParameter(int shader, int pname);
    @Deprecated
    String retrieveProgramInfoLog(int program);
    @Deprecated
    String retrieveShaderInfoLog(int shader);
    @Deprecated
    int locateUniformVariable(int program, CharSequence name);
    @Deprecated
    void assignUniformInteger(int location, int value);
    @Deprecated
    void bindAttributeLocation(int program, int index, CharSequence name);
    
    // Vertex attributes
    @Deprecated
    void configureVertexAttribute(int index, int size, int type, boolean normalized, int stride, long pointer);
    @Deprecated
    void configureVertexAttributeInteger(int index, int size, int type, int stride, long pointer);
    @Deprecated
    void activateVertexAttribute(int index);
    @Deprecated
    void deactivateVertexAttribute(int index);
    @Deprecated
    void setVertexAttribDivisor(int index, int divisor);
    
    // Synchronization
    @Deprecated
    long createFenceSync(int condition, int flags);
    @Deprecated
    int waitForSync(long sync, int flags, long timeout);
    @Deprecated
    void destroySync(long sync);
    
    // Query operations
    @Deprecated
    int queryIntegerState(int pname);
    @Deprecated
    String queryStringInfo(int name);
    @Deprecated
    int pollErrorCode();
    
    // Pixel readback
    @Deprecated
    void readFramebufferPixels(int x, int y, int width, int height, int format, int type, long pixels);
    
    // Texture queries
    @Deprecated
    int queryTextureLevelParameter(int target, int level, int pname);
    
    // Shader source (native)
    @Deprecated
    void uploadShaderSource(int shader, long pointerBufferAddress, int stringCount, long lengthsPointer);
    
    // Uniform block operations
    @Deprecated
    int locateUniformBlock(int program, String uniformBlockName);
    @Deprecated
    void bindUniformBlock(int program, int uniformBlockIndex, int uniformBlockBinding);
    @Deprecated
    String retrieveActiveUniformBlockName(int program, int uniformBlockIndex);
    
    // Timer query operations
    @Deprecated
    int generateQueryObject();
    @Deprecated
    void initiateQuery(int target, int id);
    @Deprecated
    void concludeQuery(int target);
    @Deprecated
    void disposeQueryObject(int id);
    @Deprecated
    int retrieveQueryObjectInt(int id, int pname);
    @Deprecated
    long retrieveQueryObjectInt64(int id, int pname);
    
    // Debug label operations (KHR_debug)
    @Deprecated
    void labelDebugObject(int identifier, int name, String label);
    @Deprecated
    void enterDebugGroup(int source, int id, CharSequence message);
    @Deprecated
    void exitDebugGroup();
    
    // Debug label operations (EXT_debug_label)
    @Deprecated
    void labelObjectExt(int type, int object, String label);
    
    // Debug system initialization (wraps entire debug setup)
    @Deprecated
    boolean supportsKhrDebug();
    @Deprecated
    boolean supportsArbDebugOutput();
    @Deprecated
    void setupKhrDebugSystem(int verbosityLevel, boolean synchronous, java.util.function.Consumer<String> messageHandler);
    @Deprecated
    void setupArbDebugSystem(int verbosityLevel, boolean synchronous, java.util.function.Consumer<String> messageHandler);
    
    // Extension capability checking
    @Deprecated
    boolean hasBufferStorageExtension();
    @Deprecated
    boolean hasVertexAttribBindingExtension();
    
    // ARB vertex attrib binding operations
    @Deprecated
    void attachVertexBuffer(int bindingIndex, int buffer, long offset, int stride);
    @Deprecated
    void specifyVertexAttribFormat(int attribIndex, int size, int type, boolean normalized, int relativeOffset);
    @Deprecated
    void specifyVertexAttribIFormat(int attribIndex, int size, int type, int relativeOffset);
    @Deprecated
    void associateVertexAttrib(int attribIndex, int bindingIndex);
    
    // Clear operations
    @Deprecated
    void setClearDepthValue(double depth);
    @Deprecated
    void setClearColorValue(float red, float green, float blue, float alpha);
    @Deprecated
    void selectDrawBuffer(int mode);
    
    // Advanced drawing operations
    @Deprecated
    void renderIndexedInstancedWithBase(int mode, int count, int type, long indices, int instanceCount, int baseVertex);
    @Deprecated
    void renderIndexedWithBase(int mode, int count, int type, long indices, int baseVertex);
    @Deprecated
    void renderIndexedInstanced(int mode, int count, int type, long indices, int instanceCount);
    @Deprecated
    void renderArraysInstanced(int mode, int first, int count, int instanceCount);
    
    // Uniform buffer operations
    @Deprecated
    void attachUniformBufferRange(int target, int index, int buffer, long offset, long size);
    
    // Texture buffer operations
    @Deprecated
    void attachBufferToTexture(int target, int internalFormat, int buffer);
    
    // Uniform operations (additional)
    @Deprecated
    void assignUniformFloat(int location, float value);
    @Deprecated
    void assignUniformFloat2(int location, float x, float y);
    @Deprecated
    void assignUniformFloat2v(int location, float[] value);
    @Deprecated
    void assignUniformFloat3(int location, float x, float y, float z);
    @Deprecated
    void assignUniformFloat3v(int location, float[] value);
    @Deprecated
    void assignUniformFloat4(int location, float x, float y, float z, float w);
    @Deprecated
    void assignUniformFloat4v(int location, float[] value);
    @Deprecated
    void assignUniformMatrix4f(int location, java.nio.FloatBuffer matrix);
    @Deprecated
    void bindUniformBufferBase(int bindingPoint, int bufferId);
    
    // Program fragment data binding
    @Deprecated
    void bindFragmentDataLocation(int program, int colorNumber, CharSequence name);
    
    // Sync query operations
    @Deprecated
    int querySyncStatus(long sync, int pname, java.nio.IntBuffer length);
    
    // Graphics Capabilities
    @Deprecated
    GraphicsCapabilities obtainGraphicsCapabilities();
    @Deprecated
    GraphicsCapabilities initializeGraphicsCapabilities();
    @Deprecated
    boolean checkFunctionAvailable(String functionName);
    
    // Additional buffer operations for Sodium
    @Deprecated
    void copyBufferSubData(int readTarget, int writeTarget, long readOffset, long writeOffset, long size);
    @Deprecated
    void deleteVertexArray(int vertexArray);
    @Deprecated
    void flushMappedBufferRange(int target, long offset, long length);
    
    // Buffer storage operations
    @Deprecated
    void createBufferStorage(int target, long size, int flags);
    @Deprecated
    void createBufferStorage(int target, ByteBuffer data, int flags);
    
    // Multi-draw operations
    @Deprecated
    void multiDrawElementsBaseVertex(int mode, long pCount, int type, long pIndices, int drawCount, long pBaseVertex);
    
    // Uniform matrix operations
    @Deprecated
    void assignUniformMatrix4fv(int location, boolean transpose, FloatBuffer value);
    
    // String queries
    @Deprecated
    String queryString(int name);
    @Deprecated
    String queryStringIndexed(int name, int index);
    
    // Native shader source upload
    @Deprecated
    void uploadShaderSourceNative(int shader, int count, long strings, long length);
    
    // Texture operations
    @Deprecated
    void glCopyTexSubImage2D(int target, int level, int xoffset, int yoffset, int x, int y, int width, int height);
    
    // Clear texture image (ARB_clear_texture)
    @Deprecated
    void clearTexImage(int texture, int level, int format, int type, int[] data);
    
    // Parallel shader compile (KHR/ARB)
    @Deprecated
    void setMaxShaderCompilerThreads(int count);
    
    // Capabilities
    @Deprecated
    GraphicsCapabilities getGraphicsCapabilities();
    
    // Debug object labeling
    @Deprecated
    void labelObject(int identifier, int name, String label);
    
    // Debug group push/pop
    @Deprecated
    void pushDebugGroup(int source, int id, String message);
    @Deprecated
    void popDebugGroup();
    
    // Additional methods for IrisRenderSystem
    @Deprecated
    void glGetIntegerv(int pname, int[] params);
    @Deprecated
    void glGetFloatv(int pname, float[] params);
    @Deprecated
    void glTexImage1D(int target, int level, int internalformat, int width, int border, int format, int type, java.nio.ByteBuffer pixels);
    @Deprecated
    void glTexImage2D(int target, int level, int internalformat, int width, int height, int border, int format, int type, java.nio.ByteBuffer pixels);
    @Deprecated
    void glTexImage3D(int target, int level, int internalformat, int width, int height, int depth, int border, int format, int type, java.nio.ByteBuffer pixels);
    @Deprecated
    void glUniformMatrix4fv(int location, boolean transpose, java.nio.FloatBuffer matrix);
    @Deprecated
    void glUniformMatrix4fv(int location, boolean transpose, float[] matrix);
    @Deprecated
    void glCopyTexImage2D(int target, int level, int internalFormat, int x, int y, int width, int height, int border);
    @Deprecated
    void glUniform1f(int location, float v0);
    @Deprecated
    void glUniform2f(int location, float v0, float v1);
    @Deprecated
    void glUniform2i(int location, int v0, int v1);
    @Deprecated
    void glUniform3f(int location, float v0, float v1, float v2);
    @Deprecated
    void glUniform3i(int location, int v0, int v1, int v2);
    @Deprecated
    void glUniform4f(int location, float v0, float v1, float v2, float v3);
    @Deprecated
    void glUniform4i(int location, int v0, int v1, int v2, int v3);
    @Deprecated
    void glTexParameteriv(int target, int pname, int[] params);
    @Deprecated
    void glTexParameteri(int target, int pname, int param);
    @Deprecated
    void glTexParameterf(int target, int pname, float param);
    @Deprecated
    String glGetProgramInfoLog(int program);
    @Deprecated
    String glGetShaderInfoLog(int shader);
    @Deprecated
    void glDrawBuffers(int[] buffers);
    @Deprecated
    void glReadBuffer(int buffer);
    @Deprecated
    void glClearBufferfv(int buffer, int drawbuffer, float[] values);
    @Deprecated
    void glClearBufferiv(int buffer, int drawbuffer, int[] values);
    @Deprecated
    void glClearBufferuiv(int buffer, int drawbuffer, int[] values);
    @Deprecated
    String glGetActiveUniform(int program, int index, int size, java.nio.IntBuffer type, java.nio.IntBuffer name);
    @Deprecated
    void glReadPixels(int x, int y, int width, int height, int format, int type, float[] pixels);
    @Deprecated
    void glBufferData(int target, float[] data, int usage);
    @Deprecated
    void glBufferData(int target, int[] data, int usage);
    @Deprecated
    void glBufferData(int target, java.nio.ByteBuffer data, int usage);
    @Deprecated
    void glBufferData(int target, long size, int usage);
    @Deprecated
    void glBufferSubData(int target, long offset, java.nio.ByteBuffer data);
    @Deprecated
    void glBufferStorage(int target, long size, int flags);
    @Deprecated
    void glBufferStorage(int target, java.nio.ByteBuffer data, int flags);
    @Deprecated
    java.nio.ByteBuffer glMapBufferRange(int target, long offset, long length, int access);
    @Deprecated
    boolean glUnmapBuffer(int target);
    @Deprecated
    boolean glIsBuffer(int buffer);
    @Deprecated
    void glBindBufferBase(int target, int index, int buffer);
    @Deprecated
    void glVertexAttrib4f(int index, float v0, float v1, float v2, float v3);
    @Deprecated
    void glDetachShader(int program, int shader);
    @Deprecated
    void glFramebufferTexture2D(int target, int attachment, int textarget, int texture, int level);
    @Deprecated
    void glFramebufferTexture(int target, int attachment, int texture, int level);
    @Deprecated
    int glGetTexParameteri(int target, int pname);
    @Deprecated
    void glBindImageTexture(int unit, int texture, int level, boolean layered, int layer, int access, int format);
    @Deprecated
    int glGetMaxImageUnits();
    @Deprecated
    void glGenBuffers(int[] buffers);
    @Deprecated
    void glClearBufferSubData(int target, int internalformat, long offset, long size, int format, int type, int[] data);
    @Deprecated
    void glGetProgramiv(int program, int pname, int[] params);
    @Deprecated
    void glDispatchCompute(int workX, int workY, int workZ);
    @Deprecated
    void glMemoryBarrier(int barriers);
    @Deprecated
    void glDisablei(int target, int index);
    @Deprecated
    void glEnablei(int target, int index);
    @Deprecated
    void glBlendFunc(int sfactor, int dfactor);
    @Deprecated
    void glBlendFuncSeparatei(int buffer, int srcRGB, int dstRGB, int srcAlpha, int dstAlpha);
    @Deprecated
    int glGetUniformBlockIndex(int program, String uniformBlockName);
    @Deprecated
    void glUniformBlockBinding(int program, int uniformBlockIndex, int uniformBlockBinding);
    @Deprecated
    int glGenSamplers();
    @Deprecated
    void glDeleteSamplers(int sampler);
    @Deprecated
    void glBindSampler(int unit, int sampler);
    @Deprecated
    void glBindSamplers(int first, int[] samplers);
    @Deprecated
    void glSamplerParameteri(int sampler, int pname, int param);
    @Deprecated
    void glSamplerParameterf(int sampler, int pname, float param);
    @Deprecated
    void glSamplerParameteriv(int sampler, int pname, int[] params);
    @Deprecated
    int glGetInteger(int pname);
    @Deprecated
    void glDeleteBuffers(int buffer);
    @Deprecated
    void glPolygonMode(int face, int mode);
    @Deprecated
    void glViewport(int x, int y, int width, int height);
    @Deprecated
    void glDispatchComputeIndirect(long offset);
    @Deprecated
    void glBindBuffer(int target, int buffer);
    @Deprecated
    String glGetStringi(int name, int index);
    @Deprecated
    void glCopyImageSubData(int srcName, int srcTarget, int srcLevel, int srcX, int srcY, int srcZ, int dstName, int dstTarget, int dstLevel, int dstX, int dstY, int dstZ, int width, int height, int depth);
    @Deprecated
    int glCheckFramebufferStatus(int target);
    @Deprecated
    void glUniformMatrix3fv(int location, boolean transpose, java.nio.FloatBuffer value);
    @Deprecated
    void glUniformMatrix3fv(int location, boolean transpose, float[] value);
    @Deprecated
    void glClearColor(float r, float g, float b, float a);
    @Deprecated
    int glGetAttribLocation(int program, CharSequence name);
    @Deprecated
    void glGenerateMipmap(int target);
    @Deprecated
    void glBlitFramebuffer(int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1, int mask, int filter);
    
    // DSA methods
    @Deprecated
    void glGenerateTextureMipmap(int texture);
    @Deprecated
    void glTextureParameteri(int texture, int pname, int param);
    @Deprecated
    void glTextureParameterf(int texture, int pname, float param);
    @Deprecated
    void glTextureParameteriv(int texture, int pname, int[] params);
    @Deprecated
    void glNamedFramebufferReadBuffer(int framebuffer, int mode);
    @Deprecated
    void glNamedFramebufferDrawBuffers(int framebuffer, int[] bufs);
    @Deprecated
    void glClearNamedFramebufferfv(int framebuffer, int buffer, int drawbuffer, float[] value);
    @Deprecated
    void glClearNamedFramebufferiv(int framebuffer, int buffer, int drawbuffer, int[] value);
    @Deprecated
    void glClearNamedFramebufferuiv(int framebuffer, int buffer, int drawbuffer, int[] value);
    @Deprecated
    int glGetTextureParameteri(int texture, int pname);
    @Deprecated
    void glCopyTextureSubImage2D(int texture, int level, int xoffset, int yoffset, int x, int y, int width, int height);
    @Deprecated
    void glBindTextureUnit(int unit, int texture);
    @Deprecated
    int glCreateBuffers();
    @Deprecated
    void glNamedBufferData(int buffer, float[] data, int usage);
    @Deprecated
    void glBlitNamedFramebuffer(int readFramebuffer, int drawFramebuffer, int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1, int mask, int filter);
    @Deprecated
    void glNamedFramebufferTexture(int framebuffer, int attachment, int texture, int level);
    @Deprecated
    int glCreateFramebuffers();
    @Deprecated
    int glCreateTextures(int target);
    
    // Additional rendering operations
    @Deprecated
    void glDrawElements(int mode, int count, int type, long indices);
    @Deprecated
    void glBlendEquation(int mode);
    @Deprecated
    void glClearDepth(double depth);
    @Deprecated
    int glGetFramebufferAttachmentParameteri(int target, int attachment, int pname);
    
    // Debug callback methods (low-level control methods only)
    @Deprecated
    void glDebugMessageControl(int source, int type, int severity, int[] ids, boolean enabled);
    @Deprecated
    void glDebugMessageControlKHR(int source, int type, int severity, int[] ids, boolean enabled);
    @Deprecated
    void glDebugMessageControlARB(int source, int type, int severity, int[] ids, boolean enabled);
    @Deprecated
    void glDebugMessageEnableAMD(int category, int severity, int[] ids, boolean enabled);
    
    // High-level debug callback wrapper methods
    @Deprecated
    void setupDebugMessageCallback(VulkanicAPI.DebugMessageCallback callback);
    @Deprecated
    void setupDebugMessageCallbackKHR(VulkanicAPI.DebugMessageCallback callback);
    @Deprecated
    void setupDebugMessageCallbackARB(VulkanicAPI.DebugMessageCallbackARB callback);
    @Deprecated
    void setupDebugMessageCallbackAMD(VulkanicAPI.DebugMessageCallbackAMD callback);
    @Deprecated
    void clearDebugMessageCallback();
    @Deprecated
    void clearDebugMessageCallbackKHR();
    @Deprecated
    void clearDebugMessageCallbackARB();
    @Deprecated
    void clearDebugMessageCallbackAMD();
    
    // GL43+ vertex attribute methods
    @Deprecated
    void bindVertexBuffer(int bindingindex, int buffer, long offset, int stride);
    @Deprecated
    void vertexAttribFormat(int attribindex, int size, int type, boolean normalized, int relativeoffset);
    @Deprecated
    void vertexAttribIFormat(int attribindex, int size, int type, int relativeoffset);
    @Deprecated
    void vertexAttribBinding(int attribindex, int bindingindex);
    
    // VAO methods
    @Deprecated
    int genVertexArrays();
    @Deprecated
    void bindVertexArray(int array);
    @Deprecated
    void deleteVertexArrays(int array);
    
    // GL context capabilities
    @Deprecated
    Object getGLCapabilities();
    @Deprecated
    void setupDebugMessageCallback(java.io.PrintStream stream);
    
    // Capability checking methods (to avoid casting GLCapabilities outside backends/opengl)
    @Deprecated
    boolean checkOpenGL32Support();
    @Deprecated
    boolean checkOpenGL33Support();
    @Deprecated
    boolean checkARBInstancedArraysSupport();
    @Deprecated
    long getNamedBufferDataPointer();
    @Deprecated
    long getBufferStoragePointer();
    @Deprecated
    long getBindVertexBufferPointer();
    @Deprecated
    long getVertexAttribBindingPointer();
    
    // Additional GL query and state methods
    @Deprecated
    boolean glIsEnabled(int cap);
    @Deprecated
    boolean glIsFramebuffer(int framebuffer);
    @Deprecated
    boolean glIsTexture(int texture);
    @Deprecated
    boolean glIsVertexArray(int array);
    @Deprecated
    boolean glIsProgram(int program);
    
    // Additional GL state methods
    @Deprecated
    void glBlendEquationSeparate(int modeRGB, int modeAlpha);
    @Deprecated
    void glStencilFunc(int func, int ref, int mask);
    
    // Additional texture methods
    @Deprecated
    int glGenTextures();
}
