package net.caffeinemc.mods.sodium.mixin.features.render.frapi;

import net.minecraft.client.renderer.SpecialBlockModelRenderer;
import java.util.function.Supplier;

/**
 * Compile-time stub for Sodium mixin accessor.
 * At runtime, this is generated by Sodium's mixin system.
 */
public interface BlockRenderDispatcherAccessor {
    Supplier<SpecialBlockModelRenderer> getSpecialRenderers();
}
