package net.caffeinemc.mods.sodium.mixin.features.render.frapi;

import net.minecraft.client.color.block.BlockColors;

/**
 * Compile-time stub for Sodium mixin accessor.
 * At runtime, this is generated by Sodium's mixin system.
 */
public interface ModelBlockRendererAccessor {
    BlockColors getBlockColors();
}
