package net.sodium.client.render.chunk.translucent_sorting.data;

import java.nio.IntBuffer;

import net.sodium.client.render.chunk.translucent_sorting.SortType;
import net.sodium.client.render.chunk.translucent_sorting.bsp_tree.UpdatedQuadsList;
import net.sodium.client.render.chunk.translucent_sorting.quad.TQuad;
import net.sodium.client.render.chunk.translucent_sorting.TranslucentGeometryCollector;
import net.sodium.client.render.chunk.vertex.format.NativeChunkMeshEncoder;
import net.minecraft.core.SectionPos;

/**
 * The base class for all types of translucent data. Subclasses are generated by
 * the geometry collector after the section is built.
 */
public abstract class TranslucentData {
    public static final int INDICES_PER_QUAD = 6;
    public static final int VERTICES_PER_QUAD = 4;
    public static final int BYTES_PER_INDEX = 4;
    public static final int BYTES_PER_QUAD = INDICES_PER_QUAD * BYTES_PER_INDEX;
    private static final int[] FIRST_QUAD_INDEX = {0};

    public final SectionPos sectionPos;

    TranslucentData(SectionPos sectionPos) {
        this.sectionPos = sectionPos;
    }

    public abstract SortType getSortType();

    public abstract boolean oldDataMatches(TranslucentGeometryCollector collector, SortType sortType, TQuad[] quads);

    public UpdatedQuadsList getUpdatedQuads() {
        return null;
    }

    public boolean meshesWereModified() {
        return this.getUpdatedQuads() != null;
    }

    public void close() {
        // no-op for translucent data without native or GPU-side ownership
    }

    /**
     * Prepares the translucent data for triggering of the given type. This is run
     * on the main thread before a sort task is scheduled.
     *
     * @param isAngleTrigger Whether the trigger is an angle trigger
     */
    public void prepareTrigger(boolean isAngleTrigger) {
        // no-op for other translucent data than GFNI dynamic
    }

    public static int vertexCountToQuadCount(int vertexCount) {
        return vertexCount / VERTICES_PER_QUAD;
    }

    public static int quadCountToIndexBytes(int quadCount) {
        return quadCount * BYTES_PER_QUAD;
    }

    public static int quadCountToVertexCount(int quadCount) {
        return quadCount * VERTICES_PER_QUAD;
    }

    public static void writeFirstQuadVertexIndexes(IntBuffer intBuffer) {
        NativeChunkMeshEncoder.writeQuadVertexIndexes(intBuffer, FIRST_QUAD_INDEX);
    }

    public static void writeQuadVertexIndexes(IntBuffer intBuffer, int[] quadIndexes) {
        NativeChunkMeshEncoder.writeQuadVertexIndexes(intBuffer, quadIndexes);
    }

    public static void writeQuadVertexIndexes(IntBuffer intBuffer, int[] quadIndexes, int quadIndexCount) {
        NativeChunkMeshEncoder.writeQuadVertexIndexes(intBuffer, quadIndexes, quadIndexCount);
    }

    public static void writeQuadVertexIndexesSortedByKey(IntBuffer intBuffer, int[] keys) {
        NativeChunkMeshEncoder.writeQuadVertexIndexesSortedByKey(intBuffer, keys);
    }

    public static void writeQuadVertexIndexesSortedByKey(IntBuffer intBuffer, int[] keys, int offset, int count) {
        NativeChunkMeshEncoder.writeQuadVertexIndexesSortedByKey(intBuffer, keys, offset, count);
    }
}
